// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-konnect/v3/internal/sdk/internal/utils"
	"github.com/kong/terraform-provider-konnect/v3/internal/sdk/models/shared"
	"net/http"
)

type CreateAiazurecontentsafetyPluginInWorkspaceRequest struct {
	// The UUID of your control plane. This variable is available in the Konnect manager.
	ControlPlaneID string `pathParam:"style=simple,explode=false,name=controlPlaneId"`
	// The name of the workspace
	Workspace                  string                            `default:"default" pathParam:"style=simple,explode=false,name=workspace"`
	AiAzureContentSafetyPlugin shared.AiAzureContentSafetyPlugin `request:"mediaType=application/json"`
}

func (c CreateAiazurecontentsafetyPluginInWorkspaceRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateAiazurecontentsafetyPluginInWorkspaceRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"controlPlaneId", "workspace", "AiAzureContentSafetyPlugin"}); err != nil {
		return err
	}
	return nil
}

func (c *CreateAiazurecontentsafetyPluginInWorkspaceRequest) GetControlPlaneID() string {
	if c == nil {
		return ""
	}
	return c.ControlPlaneID
}

func (c *CreateAiazurecontentsafetyPluginInWorkspaceRequest) GetWorkspace() string {
	if c == nil {
		return ""
	}
	return c.Workspace
}

func (c *CreateAiazurecontentsafetyPluginInWorkspaceRequest) GetAiAzureContentSafetyPlugin() shared.AiAzureContentSafetyPlugin {
	if c == nil {
		return shared.AiAzureContentSafetyPlugin{}
	}
	return c.AiAzureContentSafetyPlugin
}

type CreateAiazurecontentsafetyPluginInWorkspaceResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Created AiAzureContentSafety plugin
	AiAzureContentSafetyPlugin *shared.AiAzureContentSafetyPlugin
	// Unauthorized
	GatewayUnauthorizedError *shared.GatewayUnauthorizedError
}

func (c CreateAiazurecontentsafetyPluginInWorkspaceResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateAiazurecontentsafetyPluginInWorkspaceResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"ContentType", "StatusCode", "RawResponse"}); err != nil {
		return err
	}
	return nil
}

func (c *CreateAiazurecontentsafetyPluginInWorkspaceResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateAiazurecontentsafetyPluginInWorkspaceResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateAiazurecontentsafetyPluginInWorkspaceResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateAiazurecontentsafetyPluginInWorkspaceResponse) GetAiAzureContentSafetyPlugin() *shared.AiAzureContentSafetyPlugin {
	if c == nil {
		return nil
	}
	return c.AiAzureContentSafetyPlugin
}

func (c *CreateAiazurecontentsafetyPluginInWorkspaceResponse) GetGatewayUnauthorizedError() *shared.GatewayUnauthorizedError {
	if c == nil {
		return nil
	}
	return c.GatewayUnauthorizedError
}
