// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-konnect/v3/internal/sdk/internal/utils"
	"github.com/kong/terraform-provider-konnect/v3/internal/sdk/models/shared"
	"net/http"
)

type CreateWebsocketsizelimitPluginInWorkspaceRequest struct {
	// The UUID of your control plane. This variable is available in the Konnect manager.
	ControlPlaneID string `pathParam:"style=simple,explode=false,name=controlPlaneId"`
	// The name of the workspace
	Workspace                string                          `default:"default" pathParam:"style=simple,explode=false,name=workspace"`
	WebsocketSizeLimitPlugin shared.WebsocketSizeLimitPlugin `request:"mediaType=application/json"`
}

func (c CreateWebsocketsizelimitPluginInWorkspaceRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateWebsocketsizelimitPluginInWorkspaceRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"controlPlaneId", "workspace", "WebsocketSizeLimitPlugin"}); err != nil {
		return err
	}
	return nil
}

func (c *CreateWebsocketsizelimitPluginInWorkspaceRequest) GetControlPlaneID() string {
	if c == nil {
		return ""
	}
	return c.ControlPlaneID
}

func (c *CreateWebsocketsizelimitPluginInWorkspaceRequest) GetWorkspace() string {
	if c == nil {
		return ""
	}
	return c.Workspace
}

func (c *CreateWebsocketsizelimitPluginInWorkspaceRequest) GetWebsocketSizeLimitPlugin() shared.WebsocketSizeLimitPlugin {
	if c == nil {
		return shared.WebsocketSizeLimitPlugin{}
	}
	return c.WebsocketSizeLimitPlugin
}

type CreateWebsocketsizelimitPluginInWorkspaceResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Created WebsocketSizeLimit plugin
	WebsocketSizeLimitPlugin *shared.WebsocketSizeLimitPlugin
	// Unauthorized
	GatewayUnauthorizedError *shared.GatewayUnauthorizedError
}

func (c CreateWebsocketsizelimitPluginInWorkspaceResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateWebsocketsizelimitPluginInWorkspaceResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"ContentType", "StatusCode", "RawResponse"}); err != nil {
		return err
	}
	return nil
}

func (c *CreateWebsocketsizelimitPluginInWorkspaceResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateWebsocketsizelimitPluginInWorkspaceResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateWebsocketsizelimitPluginInWorkspaceResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateWebsocketsizelimitPluginInWorkspaceResponse) GetWebsocketSizeLimitPlugin() *shared.WebsocketSizeLimitPlugin {
	if c == nil {
		return nil
	}
	return c.WebsocketSizeLimitPlugin
}

func (c *CreateWebsocketsizelimitPluginInWorkspaceResponse) GetGatewayUnauthorizedError() *shared.GatewayUnauthorizedError {
	if c == nil {
		return nil
	}
	return c.GatewayUnauthorizedError
}
