// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-konnect/v3/internal/sdk/internal/utils"
	"github.com/kong/terraform-provider-konnect/v3/internal/sdk/models/shared"
	"net/http"
)

type DeleteAiGatewayConfigStoreRequest struct {
	// The unique ID of the AI Gateway.
	GatewayID string `pathParam:"style=simple,explode=false,name=gatewayId"`
	// The unique ID of the AI Gateway Config Store.
	ConfigStoreID string `pathParam:"style=simple,explode=false,name=configStoreIdOrName"`
	// If true, delete the Config Store and all its secrets. If false, deletion is rejected when secrets are still linked to the Config Store.
	Force *bool `default:"false" queryParam:"style=form,explode=true,name=force"`
}

func (d DeleteAiGatewayConfigStoreRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteAiGatewayConfigStoreRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"gatewayId", "configStoreIdOrName"}); err != nil {
		return err
	}
	return nil
}

func (d *DeleteAiGatewayConfigStoreRequest) GetGatewayID() string {
	if d == nil {
		return ""
	}
	return d.GatewayID
}

func (d *DeleteAiGatewayConfigStoreRequest) GetConfigStoreID() string {
	if d == nil {
		return ""
	}
	return d.ConfigStoreID
}

func (d *DeleteAiGatewayConfigStoreRequest) GetForce() *bool {
	if d == nil {
		return nil
	}
	return d.Force
}

type DeleteAiGatewayConfigStoreResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Bad Request
	BadRequestError *shared.BadRequestError
	// Unauthorized
	UnauthorizedError *shared.UnauthorizedError
	// Forbidden
	ForbiddenError *shared.ForbiddenError
	// Not Found
	NotFoundError *shared.NotFoundError
	// Too Many Requests
	TooManyRequestsError *shared.TooManyRequestsError
}

func (d DeleteAiGatewayConfigStoreResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteAiGatewayConfigStoreResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"ContentType", "StatusCode", "RawResponse"}); err != nil {
		return err
	}
	return nil
}

func (d *DeleteAiGatewayConfigStoreResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteAiGatewayConfigStoreResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteAiGatewayConfigStoreResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DeleteAiGatewayConfigStoreResponse) GetBadRequestError() *shared.BadRequestError {
	if d == nil {
		return nil
	}
	return d.BadRequestError
}

func (d *DeleteAiGatewayConfigStoreResponse) GetUnauthorizedError() *shared.UnauthorizedError {
	if d == nil {
		return nil
	}
	return d.UnauthorizedError
}

func (d *DeleteAiGatewayConfigStoreResponse) GetForbiddenError() *shared.ForbiddenError {
	if d == nil {
		return nil
	}
	return d.ForbiddenError
}

func (d *DeleteAiGatewayConfigStoreResponse) GetNotFoundError() *shared.NotFoundError {
	if d == nil {
		return nil
	}
	return d.NotFoundError
}

func (d *DeleteAiGatewayConfigStoreResponse) GetTooManyRequestsError() *shared.TooManyRequestsError {
	if d == nil {
		return nil
	}
	return d.TooManyRequestsError
}
