// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-konnect/v3/internal/sdk/internal/utils"
	"github.com/kong/terraform-provider-konnect/v3/internal/sdk/models/shared"
	"net/http"
)

type GetAiGatewayConsumerRequest struct {
	// The unique ID of the AI Gateway.
	GatewayID string `pathParam:"style=simple,explode=false,name=gatewayId"`
	// The unique ID of the AI Gateway consumer.
	ConsumerID string `pathParam:"style=simple,explode=false,name=consumerIdOrName"`
}

func (g GetAiGatewayConsumerRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAiGatewayConsumerRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"gatewayId", "consumerIdOrName"}); err != nil {
		return err
	}
	return nil
}

func (g *GetAiGatewayConsumerRequest) GetGatewayID() string {
	if g == nil {
		return ""
	}
	return g.GatewayID
}

func (g *GetAiGatewayConsumerRequest) GetConsumerID() string {
	if g == nil {
		return ""
	}
	return g.ConsumerID
}

type GetAiGatewayConsumerResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// A successful response returning an AI Gateway Consumer.
	AIGatewayConsumer *shared.AIGatewayConsumer
	// Unauthorized
	UnauthorizedError *shared.UnauthorizedError
	// Forbidden
	ForbiddenError *shared.ForbiddenError
	// Not Found
	NotFoundError *shared.NotFoundError
	// Too Many Requests
	TooManyRequestsError *shared.TooManyRequestsError
}

func (g GetAiGatewayConsumerResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAiGatewayConsumerResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"ContentType", "StatusCode", "RawResponse"}); err != nil {
		return err
	}
	return nil
}

func (g *GetAiGatewayConsumerResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetAiGatewayConsumerResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetAiGatewayConsumerResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetAiGatewayConsumerResponse) GetAIGatewayConsumer() *shared.AIGatewayConsumer {
	if g == nil {
		return nil
	}
	return g.AIGatewayConsumer
}

func (g *GetAiGatewayConsumerResponse) GetUnauthorizedError() *shared.UnauthorizedError {
	if g == nil {
		return nil
	}
	return g.UnauthorizedError
}

func (g *GetAiGatewayConsumerResponse) GetForbiddenError() *shared.ForbiddenError {
	if g == nil {
		return nil
	}
	return g.ForbiddenError
}

func (g *GetAiGatewayConsumerResponse) GetNotFoundError() *shared.NotFoundError {
	if g == nil {
		return nil
	}
	return g.NotFoundError
}

func (g *GetAiGatewayConsumerResponse) GetTooManyRequestsError() *shared.TooManyRequestsError {
	if g == nil {
		return nil
	}
	return g.TooManyRequestsError
}
