// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-konnect/v3/internal/sdk/models/shared"
	"net/http"
)

type GetZipkinPluginRequest struct {
	// ID of the Plugin to lookup
	PluginID string `pathParam:"style=simple,explode=false,name=PluginId"`
	// The UUID of your control plane. This variable is available in the Konnect manager.
	ControlPlaneID string `pathParam:"style=simple,explode=false,name=controlPlaneId"`
}

func (g *GetZipkinPluginRequest) GetPluginID() string {
	if g == nil {
		return ""
	}
	return g.PluginID
}

func (g *GetZipkinPluginRequest) GetControlPlaneID() string {
	if g == nil {
		return ""
	}
	return g.ControlPlaneID
}

type GetZipkinPluginResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Zipkin plugin
	ZipkinPlugin *shared.ZipkinPlugin
	// Unauthorized
	GatewayUnauthorizedError *shared.GatewayUnauthorizedError
}

func (g *GetZipkinPluginResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetZipkinPluginResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetZipkinPluginResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetZipkinPluginResponse) GetZipkinPlugin() *shared.ZipkinPlugin {
	if g == nil {
		return nil
	}
	return g.ZipkinPlugin
}

func (g *GetZipkinPluginResponse) GetGatewayUnauthorizedError() *shared.GatewayUnauthorizedError {
	if g == nil {
		return nil
	}
	return g.GatewayUnauthorizedError
}
