// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-konnect/v3/internal/sdk/internal/utils"
	"github.com/kong/terraform-provider-konnect/v3/internal/sdk/models/shared"
	"net/http"
)

type RemoveDeveloperFromPortalTeamRequest struct {
	// The Portal identifier
	PortalID string `pathParam:"style=simple,explode=false,name=portalId"`
	// ID of the developer.
	DeveloperID string `pathParam:"style=simple,explode=false,name=developerId"`
	// ID of the team.
	TeamID string `pathParam:"style=simple,explode=false,name=teamId"`
}

func (r RemoveDeveloperFromPortalTeamRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RemoveDeveloperFromPortalTeamRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, []string{"portalId", "developerId", "teamId"}); err != nil {
		return err
	}
	return nil
}

func (r *RemoveDeveloperFromPortalTeamRequest) GetPortalID() string {
	if r == nil {
		return ""
	}
	return r.PortalID
}

func (r *RemoveDeveloperFromPortalTeamRequest) GetDeveloperID() string {
	if r == nil {
		return ""
	}
	return r.DeveloperID
}

func (r *RemoveDeveloperFromPortalTeamRequest) GetTeamID() string {
	if r == nil {
		return ""
	}
	return r.TeamID
}

type RemoveDeveloperFromPortalTeamResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Unauthorized
	UnauthorizedError *shared.UnauthorizedError
	// Forbidden
	ForbiddenError *shared.ForbiddenError
	// Not Found
	NotFoundError *shared.NotFoundError
}

func (r RemoveDeveloperFromPortalTeamResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RemoveDeveloperFromPortalTeamResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, []string{"ContentType", "StatusCode", "RawResponse"}); err != nil {
		return err
	}
	return nil
}

func (r *RemoveDeveloperFromPortalTeamResponse) GetContentType() string {
	if r == nil {
		return ""
	}
	return r.ContentType
}

func (r *RemoveDeveloperFromPortalTeamResponse) GetStatusCode() int {
	if r == nil {
		return 0
	}
	return r.StatusCode
}

func (r *RemoveDeveloperFromPortalTeamResponse) GetRawResponse() *http.Response {
	if r == nil {
		return nil
	}
	return r.RawResponse
}

func (r *RemoveDeveloperFromPortalTeamResponse) GetUnauthorizedError() *shared.UnauthorizedError {
	if r == nil {
		return nil
	}
	return r.UnauthorizedError
}

func (r *RemoveDeveloperFromPortalTeamResponse) GetForbiddenError() *shared.ForbiddenError {
	if r == nil {
		return nil
	}
	return r.ForbiddenError
}

func (r *RemoveDeveloperFromPortalTeamResponse) GetNotFoundError() *shared.NotFoundError {
	if r == nil {
		return nil
	}
	return r.NotFoundError
}
