// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-konnect/v3/internal/sdk/internal/utils"
	"github.com/kong/terraform-provider-konnect/v3/internal/sdk/models/shared"
	"net/http"
)

type UpdateApplicationRequest struct {
	// The Portal identifier
	PortalID string `pathParam:"style=simple,explode=false,name=portalId"`
	// ID of the application.
	ApplicationID string `pathParam:"style=simple,explode=false,name=applicationId"`
	// Update an application.
	UpdateApplicationRequest shared.UpdateApplicationRequest `request:"mediaType=application/json"`
}

func (u UpdateApplicationRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateApplicationRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, []string{"portalId", "applicationId", "UpdateApplicationRequest"}); err != nil {
		return err
	}
	return nil
}

func (u *UpdateApplicationRequest) GetPortalID() string {
	if u == nil {
		return ""
	}
	return u.PortalID
}

func (u *UpdateApplicationRequest) GetApplicationID() string {
	if u == nil {
		return ""
	}
	return u.ApplicationID
}

func (u *UpdateApplicationRequest) GetUpdateApplicationRequest() shared.UpdateApplicationRequest {
	if u == nil {
		return shared.UpdateApplicationRequest{}
	}
	return u.UpdateApplicationRequest
}

type UpdateApplicationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Details about an application in a portal.
	GetApplicationResponse *shared.GetApplicationResponse
	// Bad Request
	BadRequestError *shared.BadRequestError
	// Unauthorized
	UnauthorizedError *shared.UnauthorizedError
	// Forbidden
	ForbiddenError *shared.ForbiddenError
	// Not Found
	NotFoundError *shared.NotFoundError
}

func (u UpdateApplicationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateApplicationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, []string{"ContentType", "StatusCode", "RawResponse"}); err != nil {
		return err
	}
	return nil
}

func (u *UpdateApplicationResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateApplicationResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateApplicationResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateApplicationResponse) GetGetApplicationResponse() *shared.GetApplicationResponse {
	if u == nil {
		return nil
	}
	return u.GetApplicationResponse
}

func (u *UpdateApplicationResponse) GetBadRequestError() *shared.BadRequestError {
	if u == nil {
		return nil
	}
	return u.BadRequestError
}

func (u *UpdateApplicationResponse) GetUnauthorizedError() *shared.UnauthorizedError {
	if u == nil {
		return nil
	}
	return u.UnauthorizedError
}

func (u *UpdateApplicationResponse) GetForbiddenError() *shared.ForbiddenError {
	if u == nil {
		return nil
	}
	return u.ForbiddenError
}

func (u *UpdateApplicationResponse) GetNotFoundError() *shared.NotFoundError {
	if u == nil {
		return nil
	}
	return u.NotFoundError
}
