// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/kong/terraform-provider-konnect/v3/internal/sdk/internal/utils"
	"github.com/kong/terraform-provider-konnect/v3/internal/sdk/models/shared"
	"net/http"
)

type UpdateRequesttransformeradvancedPluginInWorkspaceRequest struct {
	// ID of the Plugin to lookup
	PluginID string `pathParam:"style=simple,explode=false,name=PluginId"`
	// The UUID of your control plane. This variable is available in the Konnect manager.
	ControlPlaneID string `pathParam:"style=simple,explode=false,name=controlPlaneId"`
	// The name of the workspace
	Workspace                        string                                  `default:"default" pathParam:"style=simple,explode=false,name=workspace"`
	RequestTransformerAdvancedPlugin shared.RequestTransformerAdvancedPlugin `request:"mediaType=application/json"`
}

func (u UpdateRequesttransformeradvancedPluginInWorkspaceRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateRequesttransformeradvancedPluginInWorkspaceRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, []string{"PluginId", "controlPlaneId", "workspace", "RequestTransformerAdvancedPlugin"}); err != nil {
		return err
	}
	return nil
}

func (u *UpdateRequesttransformeradvancedPluginInWorkspaceRequest) GetPluginID() string {
	if u == nil {
		return ""
	}
	return u.PluginID
}

func (u *UpdateRequesttransformeradvancedPluginInWorkspaceRequest) GetControlPlaneID() string {
	if u == nil {
		return ""
	}
	return u.ControlPlaneID
}

func (u *UpdateRequesttransformeradvancedPluginInWorkspaceRequest) GetWorkspace() string {
	if u == nil {
		return ""
	}
	return u.Workspace
}

func (u *UpdateRequesttransformeradvancedPluginInWorkspaceRequest) GetRequestTransformerAdvancedPlugin() shared.RequestTransformerAdvancedPlugin {
	if u == nil {
		return shared.RequestTransformerAdvancedPlugin{}
	}
	return u.RequestTransformerAdvancedPlugin
}

type UpdateRequesttransformeradvancedPluginInWorkspaceResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// RequestTransformerAdvanced plugin
	RequestTransformerAdvancedPlugin *shared.RequestTransformerAdvancedPlugin
	// Unauthorized
	GatewayUnauthorizedError *shared.GatewayUnauthorizedError
}

func (u UpdateRequesttransformeradvancedPluginInWorkspaceResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateRequesttransformeradvancedPluginInWorkspaceResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, []string{"ContentType", "StatusCode", "RawResponse"}); err != nil {
		return err
	}
	return nil
}

func (u *UpdateRequesttransformeradvancedPluginInWorkspaceResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateRequesttransformeradvancedPluginInWorkspaceResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateRequesttransformeradvancedPluginInWorkspaceResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateRequesttransformeradvancedPluginInWorkspaceResponse) GetRequestTransformerAdvancedPlugin() *shared.RequestTransformerAdvancedPlugin {
	if u == nil {
		return nil
	}
	return u.RequestTransformerAdvancedPlugin
}

func (u *UpdateRequesttransformeradvancedPluginInWorkspaceResponse) GetGatewayUnauthorizedError() *shared.GatewayUnauthorizedError {
	if u == nil {
		return nil
	}
	return u.GatewayUnauthorizedError
}
