products:
  konnect:
    match:
      - "konnect/definitions/**/openapi.yaml"
    notMatch:
      - "konnect/definitions/identity/v2/openapi.yaml"
      - "konnect/definitions/runtime-groups/v2/openapi.yaml"
      - "konnect/definitions/runtime-groups-config/v2/openapi.yaml"

  portal:
    match:
      - "portal/definitions/**/openapi.yaml"
    notMatch: []

  internal:
    match:
      - "internal/definitions/**/openapi.yaml"
    notMatch: []
