openapi: 3.0.3
info:
    title: DocumentHub Developer Api
    description: DocumentHub Developer Api
    version: '0.0.1'
    contact:
      name: Kong
      url: 'https://konghq.com'
servers:
  - url: 'http://localhost:4400/developer/v0'
    description: Local
  - url: 'http://documenthub.documenthub.svc.cluster.local:4400/developer/v0'
    description: Konnect cluster
paths:
  /{resourceKind}/{resourceId}/documents:
    get:
      summary: Get many documents
      description: Get many documents
      operationId: getManyDocuments
      parameters:
        - in: header
          name: Accept
          schema:
            $ref: '../../documenthub/common/v0/documenthub.yaml#/components/schemas/DocumentContentTypeEnum'
        - $ref: '#/components/parameters/resourceKindParam'
        - $ref: '#/components/parameters/resourceId'
        - $ref: '../../../../common/definitions/metadatas.yaml#/components/parameters/PageSize'
        - $ref: '../../../../common/definitions/metadatas.yaml#/components/parameters/PageNumber'
      responses:
        '200':
          description: Tree of documents
          content:
            'application/json':
              schema:
                $ref: '../../documenthub/common/v0/documenthub.yaml#/components/schemas/ListDocuments'
            'application/vnd.konnect.document-tree+json':
              schema:
                $ref: '../../documenthub/common/v0/documenthub.yaml#/components/schemas/ListDocumentsTree'
        '400':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/BadRequest'
      tags:
        - Customization
  /{resourceKind}/{resourceId}/documents/tree:
    get:
      description: get the document tree
      summary: get the document tree
      parameters:
        - $ref: '#/components/parameters/resourceKindParam'
        - $ref: '#/components/parameters/resourceId'
      operationId: getDocumentTree
      responses:
        '200':
          description: Tree of documents
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '../../documenthub/common/v0/documenthub.yaml#/components/schemas/DocumentTree'
        '404':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/NotFound'
      tags:
        - Customization
  /{resourceKind}/{resourceId}/documents/{documentId}:
    get:
      description: get the document by its id
      summary: get the document by its id
      parameters:
        - in: header
          name: Accept
          schema:
            $ref: '../../documenthub/common/v0/documenthub.yaml#/components/schemas/DocumentFormatContentTypeEnum'
        - $ref: '#/components/parameters/resourceKindParam'
        - $ref: '#/components/parameters/resourceId'
        - $ref: '#/components/parameters/documentId'
      operationId: getDocumentById
      responses:
        '200':
          description: Document
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/DocumentRaw'
            application/vnd.konnect.document-nodes+json:
              schema:
                $ref: '#/components/schemas/Document'
        '404':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/NotFound'
      tags:
        - Customization
  /{resourceKind}/{resourceId}/documents/slug/{slug}:
    get:
      description: get the document by its slug
      summary: get the document by its slug
      parameters:
        - in: header
          name: Accept
          schema:
            $ref: '../../documenthub/common/v0/documenthub.yaml#/components/schemas/DocumentFormatContentTypeEnum'
        - $ref: '#/components/parameters/resourceKindParam'
        - $ref: '#/components/parameters/resourceId'
        - schema:
            type: string
          name: slug
          in: path
          required: true
          description: slug of the document
          example: getting-started
      operationId: getDocumentBySlug
      responses:
        '200':
          description: Document
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/DocumentRaw'
            application/vnd.konnect.document-nodes+json:
              schema:
                $ref: '#/components/schemas/Document'
        '404':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/NotFound'
      tags:
        - Customization
  /has-documentation:
    post:
      description: Has documentation
      summary: Returns wether the resourceKind resourceId pairs has documentation
      requestBody:
        $ref: '#/components/requestBodies/HasDocumentation'
      responses:
        '200':
          description: Has Documentation response
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/HasDocumentationResponse'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ResourceKind:
      type: string
      enum: [ services ]
    HasDocumentationRequestPayload:
      type: object
      properties:
        resource_kind:
          $ref: '#/components/schemas/ResourceKind'
        resource_ids:
          type: array
          minItems: 1
          maxItems: 100
          uniqueItems: true
          items:
            type: string
            format: uuid
      required:
      - resource_kind
      - resource_ids
    HasDocumentationResponse:
      type: array
      items:
        $ref: '#/components/schemas/HasDocumentationItem'
    HasDocumentationItem:
      type: object
      properties:
        resource_kind:
          type: string
        resource_id:
          type: string
          format: uuid
        has_documentation:
          type: boolean
        document_count:
          type: integer
      required:
      - resource_kind
      - resource_id
      - has_documentation
      - document_count
    Document:
      type: object
      title: Document
      description: a document
      required:
      - id
      - slug
      - revision
      properties:
        id:
          type: string
          format: uuid
          description: the id of the document
          example: d32d905a-ed33-46a3-a093-d8f536af9a8a
        parent_document_id:
          type: string
          format: uuid
          description: the id of the parent document
          nullable: true
          example: dd4e1b98-3629-4dd3-acc0-759a726ffee2
        slug:
          type: string
          description: the slug of the document
          example: getting-started
        revision:
          $ref: '#/components/schemas/Revision'
    Revision:
      type: object
      title: Revision
      description: revision of a document
      required:
      - id
      - document_id
      - content
      - meta
      - title
      properties:
        id:
          type: string
          format: uuid
          description: the id of the revision
          example: d32d905a-ed33-46a3-a093-d8f536af9a8a
        document_id:
          type: string
          format: uuid
          description: the id of the document
          example: d32d905a-ed33-46a3-a093-d8f536af9a8a
        content:
          $ref: '../../documenthub/common/v0/documenthub_nodes.yaml#/components/schemas/DocumentBlock'
        meta:
          type: object
          description: the metadata of the document
          example: {
              "title": "Hello World",
              "description": "This is a description",
              "keywords": "hello, world"
            }
        title:
          type: string
          description: the title of the document
          example: Hello World
    DocumentRaw:
      type: object
      title: Document
      description: a document
      required:
      - id
      - slug
      - revision
      properties:
        id:
          type: string
          format: uuid
          description: the id of the document
          example: d32d905a-ed33-46a3-a093-d8f536af9a8a
        parent_document_id:
          type: string
          format: uuid
          description: the id of the parent document
          nullable: true
          example: dd4e1b98-3629-4dd3-acc0-759a726ffee2
        slug:
          type: string
          description: the slug of the document
          example: getting-started
        revision:
          $ref: '#/components/schemas/RevisionRaw'
    RevisionRaw:
      type: object
      title: Revision
      description: revision of a document
      required:
        - id
        - document_id
        - content
        - meta
        - title
      properties:
        id:
          type: string
          format: uuid
          description: the id of the revision
          example: d32d905a-ed33-46a3-a093-d8f536af9a8a
        document_id:
          type: string
          format: uuid
          description: the id of the document
          example: d32d905a-ed33-46a3-a093-d8f536af9a8a
        content:
          type: string
          description: Markdown document
        meta:
          type: object
          description: the metadata of the document
          example:
            title: Hello World
            description: This is a description
            keywords: hello, world
        title:
          type: string
          description: the title of the document
          example: Hello World
  requestBodies:
    HasDocumentation:
      description: has documentation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HasDocumentationRequestPayload'
  responses: {}
  parameters:
    resourceKindParam:
      name: resourceKind
      in: path
      required: true
      description: Kind of the Konnect resource
      example: services
      schema:
        type: string
        enum: [ services ]
    resourceId:
      name: resourceId
      in: path
      required: true
      description: Id of the Konnect resource
      example: bf138ba2-c9b1-4229-b268-04d9d8a6410b
      schema:
        type: string
        format: uuid
    documentId:
      name: documentId
      in: path
      required: true
      description: Targeted document
      example: bb84c46a-432d-4314-81e4-478614a52dcb
      schema:
        type: string
        format: uuid
security:
  - bearerAuth: []
tags:
  - name: Customization
    description: customization operations