openapi: 3.0.3
info:
    title: Internal API-Builder v1
    description: Internal api for api builder to allow updating of entities in api-builder db. 
    version: '1.0.2'
    contact:
      name: Kong
      url: 'https://konghq.com'
tags:
  - name: portal
  - name: DCR Providers
servers:
  - url: 'http://apibuilder.apibuilder.svc.cluster.local:4400/v1'
    description: Konnect cluster
paths:
  /internal/portals/{portalId}:
    parameters:
      - $ref: '../../../../common/definitions/portal.yaml#/components/parameters/PortalId'
    put: 
      summary: insert or updates portal
      description: |
        Accepts a raw database representation of the Portal in the request body.
        Accepts a raw database representation of any linked default App Auth Strategy in the response body or null if there is none.
      operationId: put-portal
      tags:
        - portal
      responses:
        '200':
          description: The portal has been updated
        '201':
          description: The portal has been created
        '400':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/BadRequest'
      requestBody:
        $ref: '#/components/requestBodies/PutPortal'
    delete: 
      summary: delete portal
      description: Deletes portal specified in path
      operationId: delete-portal
      tags:
        - portal
      responses:
        '204':
          description: No Content.
        '404':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/NotFound'

  /internal/dcr-providers/{dcrProviderId}:
    parameters:
      - $ref: '../../../../common/definitions/portal.yaml#/components/parameters/DcrProviderId'
    put:
      summary: Inserts or updates a DCR provider
      description: |
        Accepts a raw database representation of the DCR Provider in the response body
      operationId: update-dcr-provider
      requestBody:
        $ref: '#/components/requestBodies/PutDcrProvider'
      responses:
        '200':
          $ref: '#/components/responses/PutDcrProviderResponse'
        '400':
          $ref:  '../../../../common/definitions/errors.yaml#/components/responses/BadRequest'
        '401':
          $ref:  '../../../../common/definitions/errors.yaml#/components/responses/Unauthorized'
        '403':
          $ref:  '../../../../common/definitions/errors.yaml#/components/responses/Forbidden'
        '404':
          $ref:  '../../../../common/definitions/errors.yaml#/components/responses/NotFound'
      tags:
        - DCR Providers
    delete:
      summary: Deletes a DCR provider
      description: Deletes a DCR provider.
      operationId: delete-dcr-provider
      responses:
        '204':
          description: No Content.
        '401':
          $ref:  '../../../../common/definitions/errors.yaml#/components/responses/Unauthorized'
        '403':
          $ref:  '../../../../common/definitions/errors.yaml#/components/responses/Forbidden'
        '404':
          $ref:  '../../../../common/definitions/errors.yaml#/components/responses/NotFound'
      tags:
        - DCR Providers

components:
  requestBodies:
    PutPortal: 
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Portal'
    PutDcrProvider:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PutDcrProviderRequest'
          examples:
            DcrProviderRequest:
              $ref: '#/components/examples/DcrProviderPutRequest'
  responses:
    PutDcrProviderResponse:
      description: A response containing a single DCR provider object.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DcrProviderResponse'
          examples:
            DcrProviderResponse:
              $ref: '#/components/examples/DcrProviderResponse'
  schemas:
    Portal: 
      additionalProperties: true
      type: object
      required:
        - id
        - default_application_auth_strategy
        - name
        - uri
        - labels
      properties:
        id: 
          type: string
          format: uuid
        name: 
          type: string
        display_name:
          type: string
        uri:
          type: string
        custom_domain:
          type: string
        is_domain_verified:
          type: boolean
        logo:
          type: string
        logo_filename:
          type: string
        favicon:
          type: string
        favicon_filename:
          type: string
        is_public:
          type: boolean
        auto_approve_developers:
          type: boolean
        auto_approve_applications:
          type: boolean
        rbac_enabled:
          type: boolean
        config:
          type: object
          additionalProperties: true
        customization: 
          $ref: '../../../../common/definitions/portal.yaml#/components/schemas/PortalCustomization'
        labels: 
          $ref: '../../../../common/definitions/konnect_properties.yaml#/components/schemas/Labels'
        description:
          type: string
        default_application_auth_strategy: 
          $ref: '#/components/schemas/NullableAuthStrategy'
    NullableAuthStrategy:
      type: object
      nullable: true
      required: 
        - id
        - name
        - display_name
        - strategy_type
        - dcr_provider
        - configs
        - labels
      properties:
        id: 
          type: string
          format: uuid
        name:
          type: string
        display_name:
          type: string
        strategy_type:
          type: string
        configs:
          type: object
        labels:
          $ref: '../../../../common/definitions/konnect_properties.yaml#/components/schemas/Labels'
        dcr_provider: 
          $ref: '#/components/schemas/NullableDcrProvider'
    NullableDcrProvider:
      type: object
      nullable: true
      required:
        - id
        - name
        - provider_type
        - issuer
        - dcr_config
        - labels
      properties:
        id: 
          type: string
          format: uuid
        name:
          type: string
        provider_type:
          type: string 
        issuer:
          type: string
        dcr_config:
          type: object
        labels:
          $ref: '../../../../common/definitions/konnect_properties.yaml#/components/schemas/Labels'
    PutDcrProviderRequest:
      additionalProperties: true
      type: object
      title: UpdateDcrProviderRequest
      description: Updates a DCR provider.
      required:
        - id
        - name
        - provider_type
        - issuer
        - dcr_config
        - org_id
        - created_at
        - updated_at
      properties:
        id:
          type: string
          format: uuid
        org_id:
          type: string
          format: uuid
        name:
          $ref: '#/components/schemas/DcrProviderName'
        provider_type:
          type: string
          description: The type of DCR provider. Can be one of the following - auth0, azureAd, curity, okta, http
          enum:
            - auth0
            - azureAd
            - curity
            - okta
            - http
        issuer:
          type: string
          format: url
          maxLength: 256
        labels:
          $ref: '../../../../common/definitions/konnect_properties.yaml#/components/schemas/LabelsUpdate'
        dcr_config:
          anyOf:
            - $ref: '#/components/schemas/UpdateDcrConfigAuth0InRequest'
            - $ref: '#/components/schemas/UpdateDcrConfigAzureAdInRequest'
            - $ref: '#/components/schemas/UpdateDcrConfigCurityInRequest'
            - $ref: '#/components/schemas/UpdateDcrConfigOktaInRequest'
            - $ref: '#/components/schemas/UpdateDcrConfigHttpInRequest'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    DcrProviderName:
      type: string
      description: |
        The name of the DCR provider. This is used to identify the DCR provider in the Konnect UI.
      minLength: 1
      maxLength: 256
    DcrBaseUrl:
      type: string
      description: |
        The base URL of the DCR server. This is the URL that will be used to make the HTTP requests from Konnect to the DCR provider.
        This URL must be accessible from the Konnect service.
      format: url
      maxLength: 256
    UpdateDcrConfigAuth0InRequest:
      title: DcrConfigAuth0InRequest
      type: object
      description: Payload to update an Auth0 DCR provider.
      additionalProperties: false
      properties:
        initial_client_id:
          $ref: '#/components/schemas/DcrConfigPropertyInitialClientId'
        initial_client_secret:
          $ref: '#/components/schemas/DcrConfigPropertyInitialClientSecret'
        initial_client_audience:
          $ref: '#/components/schemas/DcrConfigPropertyInitialClientAudience'
        use_developer_managed_scopes:
          type: boolean
    DcrConfigPropertyInitialClientId:
      title: DcrConfigPropertyInitialClientId
      type: string
      maxLength: 256
      description: |
        This ID should be copied from your identity provider's settings after you create a client
        and assign it as the management client for DCR for this developer portal
    DcrConfigPropertyInitialClientSecret:
      title: DcrConfigPropertyInitialClientSecret
      type: string
      maxLength: 256
      description: |
        This secret should be copied from your identity provider's settings after you create a client
        and assign it as the management client for DCR for this developer portal
    DcrConfigPropertyDcrToken:
      title: DcrConfigPropertyInitialDcrToken
      type: string
      maxLength: 256
      description: |
        This secret should be copied from your identity provider's settings after you create a client
        and assign it as the management client for DCR for this developer portal
    DcrConfigPropertyInitialClientAudience:
      title: DcrConfigPropertyInitialClientAudience
      type: string
      maxLength: 256
      nullable: true
      description: |
        This is the audience value used for the initial client.
        If using a custom domain on Auth0, this must be set as to the Auth0 Management API audience value.
        If left blank, the issuer will be used instead.
    DcrConfigPropertyApiKey:
      title: DcrConfigPropertyApiKey
      type: string
      pattern: "^[a-zA-Z0-9_]+$"
      minLength: 12
      maxLength: 256
      description: |
        This is the API Key that will be sent with each HTTP request to the custom DCR server. It can be
        verified on the server to ensure that incoming requests are coming from Konnect.
    DcrConfigPropertyDisableEventHooks:
      title: DcrConfigPropertyDisableEventHooks
      type: boolean
      description: This flag disables all the event-hooks on the application flow for the DCR provider.
    DcrConfigPropertyDisableRefreshSecret:
      title: DcrConfigPropertyDisableRefreshSecret
      type: boolean
      description: This flag disable the refresh-secret endpoint on the application flow for the DCR provider.
    UpdateDcrConfigAzureAdInRequest:
      title: DcrConfigAzureAdInRequest
      type: object
      description: Payload to update an Azure AD DCR provider.
      additionalProperties: false
      properties:
        initial_client_id:
          $ref: '#/components/schemas/DcrConfigPropertyInitialClientId'
        initial_client_secret:
          $ref: '#/components/schemas/DcrConfigPropertyInitialClientSecret'
    UpdateDcrConfigHttpInRequest:
      title: CreateDcrConfigHttpInRequest
      type: object
      description: Payload to update an HTTP DCR provider.
      additionalProperties: false
      properties:
        dcr_base_url:
          $ref: '#/components/schemas/DcrBaseUrl'
        api_key:
          $ref: '#/components/schemas/DcrConfigPropertyApiKey'
        disable_event_hooks:
          $ref: '#/components/schemas/DcrConfigPropertyDisableEventHooks'
        disable_refresh_secret:
          $ref: '#/components/schemas/DcrConfigPropertyDisableRefreshSecret'
    UpdateDcrConfigCurityInRequest:
      title: DcrConfigCurityInRequest
      type: object
      description: Payload to update a Curity DCR provider.
      additionalProperties: false
      properties:
        initial_client_id:
          $ref: '#/components/schemas/DcrConfigPropertyInitialClientId'
        initial_client_secret:
          $ref: '#/components/schemas/DcrConfigPropertyInitialClientSecret'
    UpdateDcrConfigOktaInRequest:
      title: DcrConfigOktaInRequest
      type: object
      description: Payload to update an Okta DCR provider.
      additionalProperties: false
      properties:
        dcr_token:
          $ref: '#/components/schemas/DcrConfigPropertyDcrToken'
    DcrProviderResponse:
      type: object
      description:  A response containing a raw database representation of the DCR Provider.
      properties:
        id:
          $ref: '../../../../common/definitions/properties.yaml#/components/schemas/UUID'
        org_id:
          $ref: '../../../../common/definitions/properties.yaml#/components/schemas/UUID'
        name:
          $ref: '#/components/schemas/DcrProviderName'
        provider_type:
          type: string
          description: The type of DCR provider. Can be one of the following - auth0, azureAd, curity, okta, http
          enum:
            - auth0
            - azureAd
            - curity
            - okta
            - http
        issuer:
          type: string
          description: The issuer of the DCR provider.
          format: url
          maxLength: 256
        dcr_config:
          type: object
          description: The DCR configuration for this DCR provider.
        labels:
          $ref: '../../../../common/definitions/konnect_properties.yaml#/components/schemas/Labels'
        created_at:
          $ref: '../../../../common/definitions/properties.yaml#/components/schemas/CreatedAt'
        updated_at:
          $ref: '../../../../common/definitions/properties.yaml#/components/schemas/UpdatedAt'
      required:
        - id
        - org_id
        - name
        - provider_type
        - issuer
        - dcr_config
  examples:
    DcrProviderPutRequest:
      summary: DCR provider request example
      value:
        id: 93f8380e-7798-4566-99e3-2edf2b57d289
        name: DCR Auth0 1 - Segment A
        provider_type: auth0
        issuer: https://my-issuer.auth0.com/api/v2/
        dcr_config:
          initial_client_id: abc123
          initial_client_audience: https://my-custom-domain.com/api/v2/
          use_developer_managed_scopes: false
        org_id: 7f9fd312-a987-4628-b4c5-bb4f4fddd5f7
        labels: {}          
        created_at: 2023-01-01T00:00:00.000Z
        updated_at: 2023-01-01T00:00:00.000Z
    DcrProviderResponse:
      summary: DCR provider Response example
      value:
        id: 93f8380e-7798-4566-99e3-2edf2b57d289
        name: DCR Auth0 1 - Segment A
        provider_type: auth0
        issuer: https://my-issuer.auth0.com/api/v2/
        dcr_config:
          initial_client_id: abc123
          initial_client_audience: https://my-custom-domain.com/api/v2/
          use_developer_managed_scopes: false
        org_id: 7f9fd312-a987-4628-b4c5-bb4f4fddd5f7
        labels: {}          
        created_at: 2023-01-01T00:00:00.000Z
        updated_at: 2023-01-01T00:00:00.000Z