openapi: 3.0.0
info:
  title: Application Registration Configuration Api
  version: 2.0.0
  description: The API for Konnect Portal Application Registration Configuration.
  contact:
    name: Kong
    url: 'https://cloud.konghq.com'
paths:
  /api/v2/application-registrations/service-versions/{id}:
    get:
      summary: Application registration Configuration
      description: Returns the application registration configuration of the given service
      operationId: get-application-registration-configuration
      parameters:
      - in: path
        name: id
        required: true
        description: id of the service version
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: application registration configuration
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ApplicationRegistrationConfiguration'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthenticated'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
      tags:
      - app-reg
components:
  securitySchemes:
    portalAccessToken:
      $ref: '../../../../common/definitions/security.yaml#/components/securitySchemes/portalAccessToken'
  schemas:
    ApplicationRegistrationConfiguration:
      type: object
      properties:
        auto_approve:
          type: boolean
        status:
          type: string
          enum: [ enabled, pending ]
        auth_config:
          type: object
          properties:
            name:
              type: string
              enum: [ key-auth, openid-connect ]
            config:
              type: object
      required:
      - status
      - auth_config
      - auto_approve
    Error:
      type: object
      title: Error
      description: standard error
      x-examples:
        Example 1:
          status: 404
          title: Not Found
          type: https://kongapi.info/konnect/not-found
          instance: 'portal:trace:2287285207635123011'
          detail: The requested document was not found
      required:
        - status
        - title
        - instance
      properties:
        status:
          type: integer
          description: The HTTP status code.
          example: 404
        title:
          type: string
          description: The error response code.
          example: Not Found
        type:
          type: string
          description: The error type.
          example: Not Found
        instance:
          type: string
          example: 'portal:trace:2287285207635123011'
          description: The portal traceback code
        invalid_parameters:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                description: The name of the invalid parameter.
              reason:
                type: string
                description: The reason the parameter is invalid.
              field:
                type: string
                description: The field that caused the error.
                example: name
              rule:
                type: string
                description: The rule that caused the error.
                example: required
          description: An array of invalid parameters.
        detail:
          type: string
          example: The requested team was not found
          description: Details about the error.
  responses:
    Unauthenticated:
      description: Unauthenticated
      content:
        application/problem+json:
          schema:
            title: 'UnauthenticatedError'
            type: object
            description: The error response object.
            properties:
              type: 
                type: string
                description: The error type.
              status:
                type: integer
                example: 401
                description: The HTTP status code.
                enum:
                  - 401
              title:
                type: string
                description: The Error Response.
                example: Unauthenticated
              instance:
                type: string
                description: The Konnect traceback code.
                example: 'konnect:trace:952172606039454040'
              detail:
                type: string
                description: Details about the error response.
                example: A valid session is required
            required:
              - status
              - title
    BadRequest:
      description: Bad Request
      content:
        application/problem+json:
          schema:
            title: 'BadRequestError'
            type: object
            description: The error object
            properties:
              status:
                type: integer
                description: The HTTP response code
                example: 400
                enum:
                  - 400
              title:
                type: string
                example: Bad Request
                description: The Error response
              instance:
                type: string
                description: The Konnect traceback ID.
                example: 'konnect:trace:3674017986744198214'
              detail:
                type: string
                description: Information about the error response.
                example: Validation
              invalid_parameters:
                type: array
                description: An array of objects that contains information related to the error response.
                items:
                  type: object
                  additionalProperties: true
                  properties:
                    rule:
                      type: string
                    field:
                      type: string
                    reason:
                      type: string
                required:
                  - field
                  - reason
            required:
              - status
              - title
    NotFound:
      description: Not Found
      content:
        application/problem+json:
          schema:
            title: 'NotFoundError'
            type: object
            description: The error object
            properties:
              type:
                type: string
                description: The error type.
              status:
                type: integer
                description: The HTTP response code
                example: 404
                enum:
                  - 404
              title:
                type: string
                example: Not Found
                description: The Error response
              instance:
                type: string
                description: The Konnect traceback ID.
                example: 'konnect:trace:3674017986744198214'
                required:
                  - field
                  - reason
            required:
              - status
              - title
    InternalServerError:
      description: Internal Server Error
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Error'
security:
  - portalAccessToken: []
tags:
  - name: app-reg
    description: Application Registration