// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/kong/terraform-provider-konnect/v3/internal/sdk/internal/utils"
)

type ACLWithoutParentsConsumer struct {
	ID *string `json:"id,omitempty"`
}

func (a ACLWithoutParentsConsumer) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *ACLWithoutParentsConsumer) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *ACLWithoutParentsConsumer) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}

type ACLWithoutParents struct {
	Consumer *ACLWithoutParentsConsumer `json:"consumer,omitempty"`
	// Unix epoch when the resource was created.
	CreatedAt *int64 `json:"created_at,omitempty"`
	Group     string `json:"group"`
	// A string representing a UUID (universally unique identifier).
	ID *string `json:"id,omitempty"`
	// A set of strings representing tags.
	Tags []string `json:"tags"`
}

func (a ACLWithoutParents) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *ACLWithoutParents) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, []string{"group"}); err != nil {
		return err
	}
	return nil
}

func (a *ACLWithoutParents) GetConsumer() *ACLWithoutParentsConsumer {
	if a == nil {
		return nil
	}
	return a.Consumer
}

func (a *ACLWithoutParents) GetCreatedAt() *int64 {
	if a == nil {
		return nil
	}
	return a.CreatedAt
}

func (a *ACLWithoutParents) GetGroup() string {
	if a == nil {
		return ""
	}
	return a.Group
}

func (a *ACLWithoutParents) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *ACLWithoutParents) GetTags() []string {
	if a == nil {
		return nil
	}
	return a.Tags
}
