// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/kong/terraform-provider-konnect/v3/internal/sdk/internal/utils"
	"time"
)

// AIGatewayAgentType - The type of the agent.
type AIGatewayAgentType string

const (
	AIGatewayAgentTypeA2a  AIGatewayAgentType = "a2a"
	AIGatewayAgentTypeHTTP AIGatewayAgentType = "http"
)

func (e AIGatewayAgentType) ToPointer() *AIGatewayAgentType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AIGatewayAgentType) IsExact() bool {
	if e != nil {
		switch *e {
		case "a2a", "http":
			return true
		}
	}
	return false
}

// AIGatewayAgentLogging - Configuration for AI Gateway logging.
type AIGatewayAgentLogging struct {
	Payloads *bool `default:"false" json:"payloads"`
	// Maximum size in bytes for logged request/response payloads. Payloads exceeding this size will be truncated.
	MaxPayloadSize *int64 `default:"1048576" json:"max_payload_size"`
}

func (a AIGatewayAgentLogging) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AIGatewayAgentLogging) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AIGatewayAgentLogging) GetPayloads() *bool {
	if a == nil {
		return nil
	}
	return a.Payloads
}

func (a *AIGatewayAgentLogging) GetMaxPayloadSize() *int64 {
	if a == nil {
		return nil
	}
	return a.MaxPayloadSize
}

// AIGatewayAgentConfig - Configuration for the agent. The structure varies depending on the agent type.
type AIGatewayAgentConfig struct {
	// Helper field to set protocol, host, port and path of the upstream A2A Agent using a URL.
	// This is the same as a Kong Gateway Service URL: ${scheme}://${host}:${port}/${path}
	//
	URL string `json:"url"`
	// Configuration applied when proxying to the upstream service, including authentication.
	Upstream *AIGatewayUpstreamConfigOutput `json:"upstream,omitempty"`
	// Configuration for an AI Gateway route.
	Route *AIGatewayRouteConfig `json:"route,omitempty"`
	// HTTP/HTTPS proxy configuration for outbound requests to the upstream AI provider.
	Proxy *AIGatewayProxyConfigOutput `json:"proxy,omitempty"`
	// Maximum size of request body to parse. Set to 0 for unlimited.
	MaxRequestBodySize *int64 `default:"8388608" json:"max_request_body_size"`
	// Configuration for AI Gateway logging.
	Logging *AIGatewayAgentLogging `json:"logging,omitempty"`
}

func (a AIGatewayAgentConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AIGatewayAgentConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, []string{"url"}); err != nil {
		return err
	}
	return nil
}

func (a *AIGatewayAgentConfig) GetURL() string {
	if a == nil {
		return ""
	}
	return a.URL
}

func (a *AIGatewayAgentConfig) GetUpstream() *AIGatewayUpstreamConfigOutput {
	if a == nil {
		return nil
	}
	return a.Upstream
}

func (a *AIGatewayAgentConfig) GetRoute() *AIGatewayRouteConfig {
	if a == nil {
		return nil
	}
	return a.Route
}

func (a *AIGatewayAgentConfig) GetProxy() *AIGatewayProxyConfigOutput {
	if a == nil {
		return nil
	}
	return a.Proxy
}

func (a *AIGatewayAgentConfig) GetMaxRequestBodySize() *int64 {
	if a == nil {
		return nil
	}
	return a.MaxRequestBodySize
}

func (a *AIGatewayAgentConfig) GetLogging() *AIGatewayAgentLogging {
	if a == nil {
		return nil
	}
	return a.Logging
}

// AIGatewayAgent - AI Agent created successfully.
type AIGatewayAgent struct {
	// The display name for this agent.
	DisplayName string `json:"display_name"`
	// A user-defined unique identifier for this agent, used as a stable human-readable reference. This value is immutable after creation.
	Name string `json:"name"`
	// Whether the Agent is enabled.
	Enabled *bool `default:"true" json:"enabled"`
	// The type of the agent.
	Type AIGatewayAgentType `json:"type"`
	// List of policy references.
	Policies []string `json:"policies,omitempty"`
	// Access control configuration for an agent.
	Access *AIGatewayAgentAccess `json:"access,omitempty"`
	// Configuration for the agent. The structure varies depending on the agent type.
	Config AIGatewayAgentConfig `json:"config"`
	// Public labels store information about an entity that can be used for filtering a list of objects.
	//
	// Public labels are intended to store **PUBLIC** metadata.
	//
	// Keys must be of length 1-63 characters, and cannot start with "kong", "konnect", "mesh", "kic", or "_".
	//
	Labels map[string]string `json:"labels,omitempty"`
	// Stores information about what manages this entity, such as the tool or system responsible for its lifecycle (for example, `terraform`).
	//
	// Keys must be 1–63 characters long and start with an alphanumeric character.
	//
	ManagedBy map[string]string `json:"managed_by,omitempty"`
	// Contains a unique identifier used for this resource.
	ID string `json:"id"`
	// An ISO-8601 timestamp representation of entity creation date.
	CreatedAt time.Time `json:"created_at"`
	// An ISO-8601 timestamp representation of entity update date.
	UpdatedAt time.Time `json:"updated_at"`
}

func (a AIGatewayAgent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AIGatewayAgent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, []string{"display_name", "name", "type", "config", "id", "created_at", "updated_at"}); err != nil {
		return err
	}
	return nil
}

func (a *AIGatewayAgent) GetDisplayName() string {
	if a == nil {
		return ""
	}
	return a.DisplayName
}

func (a *AIGatewayAgent) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AIGatewayAgent) GetEnabled() *bool {
	if a == nil {
		return nil
	}
	return a.Enabled
}

func (a *AIGatewayAgent) GetType() AIGatewayAgentType {
	if a == nil {
		return AIGatewayAgentType("")
	}
	return a.Type
}

func (a *AIGatewayAgent) GetPolicies() []string {
	if a == nil {
		return nil
	}
	return a.Policies
}

func (a *AIGatewayAgent) GetAccess() *AIGatewayAgentAccess {
	if a == nil {
		return nil
	}
	return a.Access
}

func (a *AIGatewayAgent) GetConfig() AIGatewayAgentConfig {
	if a == nil {
		return AIGatewayAgentConfig{}
	}
	return a.Config
}

func (a *AIGatewayAgent) GetLabels() map[string]string {
	if a == nil {
		return nil
	}
	return a.Labels
}

func (a *AIGatewayAgent) GetManagedBy() map[string]string {
	if a == nil {
		return nil
	}
	return a.ManagedBy
}

func (a *AIGatewayAgent) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *AIGatewayAgent) GetCreatedAt() time.Time {
	if a == nil {
		return time.Time{}
	}
	return a.CreatedAt
}

func (a *AIGatewayAgent) GetUpdatedAt() time.Time {
	if a == nil {
		return time.Time{}
	}
	return a.UpdatedAt
}
