// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/kong/terraform-provider-konnect/v3/internal/sdk/internal/utils"
)

type AWSPrivateHostedZoneType string

const (
	AWSPrivateHostedZoneTypeAwsPrivateHostedZoneAttachment AWSPrivateHostedZoneType = "aws-private-hosted-zone-attachment"
)

func (e AWSPrivateHostedZoneType) ToPointer() *AWSPrivateHostedZoneType {
	return &e
}
func (e *AWSPrivateHostedZoneType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "aws-private-hosted-zone-attachment":
		*e = AWSPrivateHostedZoneType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AWSPrivateHostedZoneType: %v", v)
	}
}

type AwsPrivateHostedZoneAttachmentConfig struct {
	Kind AWSPrivateHostedZoneType `json:"kind"`
	// AWS Hosted Zone to create attachment to.
	HostedZoneID string `json:"hosted_zone_id"`
}

func (a AwsPrivateHostedZoneAttachmentConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AwsPrivateHostedZoneAttachmentConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, []string{"kind", "hosted_zone_id"}); err != nil {
		return err
	}
	return nil
}

func (a *AwsPrivateHostedZoneAttachmentConfig) GetKind() AWSPrivateHostedZoneType {
	if a == nil {
		return AWSPrivateHostedZoneType("")
	}
	return a.Kind
}

func (a *AwsPrivateHostedZoneAttachmentConfig) GetHostedZoneID() string {
	if a == nil {
		return ""
	}
	return a.HostedZoneID
}
