// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// ConsumeKeyValidationAction - Defines a behavior when record key is not valid.
//   - mark - marks a record with kong/server header and client ID value
//     to help to identify the clients violating schema.
//   - skip - skips delivering a record.
type ConsumeKeyValidationAction string

const (
	ConsumeKeyValidationActionMark ConsumeKeyValidationAction = "mark"
	ConsumeKeyValidationActionSkip ConsumeKeyValidationAction = "skip"
)

func (e ConsumeKeyValidationAction) ToPointer() *ConsumeKeyValidationAction {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ConsumeKeyValidationAction) IsExact() bool {
	if e != nil {
		switch *e {
		case "mark", "skip":
			return true
		}
	}
	return false
}
