// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// EventGatewayStaticKeyCreate - A symmetric key with its secret value for creation.
type EventGatewayStaticKeyCreate struct {
	// The unique name of the static key.
	Name string `json:"name"`
	// A human-readable description of the static key.
	Description *string `json:"description,omitempty"`
	// Labels store metadata of an entity that can be used for filtering an entity list or for searching across entity types.
	//
	// Keys must be of length 1-63 characters, and cannot start with "kong", "konnect", "mesh", "kic", or "_".
	//
	Labels map[string]*string `json:"labels,omitempty"`
	// A sensitive value containing the secret or a reference to a secret as a template string expression.
	// If the value is provided as plain text, it is encrypted at rest and omitted from API responses.
	// If provided as an expression, the expression itself is stored and returned by the API.
	//
	Value string `json:"value"`
}

func (e *EventGatewayStaticKeyCreate) GetName() string {
	if e == nil {
		return ""
	}
	return e.Name
}

func (e *EventGatewayStaticKeyCreate) GetDescription() *string {
	if e == nil {
		return nil
	}
	return e.Description
}

func (e *EventGatewayStaticKeyCreate) GetLabels() map[string]*string {
	if e == nil {
		return nil
	}
	return e.Labels
}

func (e *EventGatewayStaticKeyCreate) GetValue() string {
	if e == nil {
		return ""
	}
	return e.Value
}
