// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/kong/terraform-provider-konnect/v3/internal/sdk/internal/utils"
)

type ExitTransformerPluginAfter struct {
	Access []string `json:"access,omitempty"`
}

func (e *ExitTransformerPluginAfter) GetAccess() []string {
	if e == nil {
		return nil
	}
	return e.Access
}

type ExitTransformerPluginBefore struct {
	Access []string `json:"access,omitempty"`
}

func (e *ExitTransformerPluginBefore) GetAccess() []string {
	if e == nil {
		return nil
	}
	return e.Access
}

type ExitTransformerPluginOrdering struct {
	After  *ExitTransformerPluginAfter  `json:"after,omitempty"`
	Before *ExitTransformerPluginBefore `json:"before,omitempty"`
}

func (e *ExitTransformerPluginOrdering) GetAfter() *ExitTransformerPluginAfter {
	if e == nil {
		return nil
	}
	return e.After
}

func (e *ExitTransformerPluginOrdering) GetBefore() *ExitTransformerPluginBefore {
	if e == nil {
		return nil
	}
	return e.Before
}

type ExitTransformerPluginPartials struct {
	// A string representing a UUID (universally unique identifier).
	ID *string `json:"id,omitempty"`
	// A unique string representing a UTF-8 encoded name.
	Name *string `json:"name,omitempty"`
	Path *string `json:"path,omitempty"`
}

func (e *ExitTransformerPluginPartials) GetID() *string {
	if e == nil {
		return nil
	}
	return e.ID
}

func (e *ExitTransformerPluginPartials) GetName() *string {
	if e == nil {
		return nil
	}
	return e.Name
}

func (e *ExitTransformerPluginPartials) GetPath() *string {
	if e == nil {
		return nil
	}
	return e.Path
}

type ExitTransformerPluginConfig struct {
	Functions []string `json:"functions"`
	// Determines whether to handle unexpected errors by transforming their responses.
	HandleUnexpected *bool `default:"false" json:"handle_unexpected"`
	// Determines whether to handle unknown status codes by transforming their responses.
	HandleUnknown *bool `default:"false" json:"handle_unknown"`
}

func (e ExitTransformerPluginConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ExitTransformerPluginConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *ExitTransformerPluginConfig) GetFunctions() []string {
	if e == nil {
		return []string{}
	}
	return e.Functions
}

func (e *ExitTransformerPluginConfig) GetHandleUnexpected() *bool {
	if e == nil {
		return nil
	}
	return e.HandleUnexpected
}

func (e *ExitTransformerPluginConfig) GetHandleUnknown() *bool {
	if e == nil {
		return nil
	}
	return e.HandleUnknown
}

// ExitTransformerPluginConsumer - If set, the plugin will activate only for requests where the specified has been authenticated. (Note that some plugins can not be restricted to consumers this way.). Leave unset for the plugin to activate regardless of the authenticated Consumer.
type ExitTransformerPluginConsumer struct {
	ID *string `json:"id,omitempty"`
}

func (e *ExitTransformerPluginConsumer) GetID() *string {
	if e == nil {
		return nil
	}
	return e.ID
}

type ExitTransformerPluginProtocols string

const (
	ExitTransformerPluginProtocolsGrpc  ExitTransformerPluginProtocols = "grpc"
	ExitTransformerPluginProtocolsGrpcs ExitTransformerPluginProtocols = "grpcs"
	ExitTransformerPluginProtocolsHTTP  ExitTransformerPluginProtocols = "http"
	ExitTransformerPluginProtocolsHTTPS ExitTransformerPluginProtocols = "https"
)

func (e ExitTransformerPluginProtocols) ToPointer() *ExitTransformerPluginProtocols {
	return &e
}
func (e *ExitTransformerPluginProtocols) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "grpc":
		fallthrough
	case "grpcs":
		fallthrough
	case "http":
		fallthrough
	case "https":
		*e = ExitTransformerPluginProtocols(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ExitTransformerPluginProtocols: %v", v)
	}
}

// ExitTransformerPluginRoute - If set, the plugin will only activate when receiving requests via the specified route. Leave unset for the plugin to activate regardless of the route being used.
type ExitTransformerPluginRoute struct {
	ID *string `json:"id,omitempty"`
}

func (e *ExitTransformerPluginRoute) GetID() *string {
	if e == nil {
		return nil
	}
	return e.ID
}

// ExitTransformerPluginService - If set, the plugin will only activate when receiving requests via one of the routes belonging to the specified Service. Leave unset for the plugin to activate regardless of the Service being matched.
type ExitTransformerPluginService struct {
	ID *string `json:"id,omitempty"`
}

func (e *ExitTransformerPluginService) GetID() *string {
	if e == nil {
		return nil
	}
	return e.ID
}

// ExitTransformerPlugin - A Plugin entity represents a plugin configuration that will be executed during the HTTP request/response lifecycle. It is how you can add functionalities to Services that run behind Kong, like Authentication or Rate Limiting for example. You can find more information about how to install and what values each plugin takes by visiting the [Kong Hub](https://docs.konghq.com/hub/). When adding a Plugin Configuration to a Service, every request made by a client to that Service will run said Plugin. If a Plugin needs to be tuned to different values for some specific Consumers, you can do so by creating a separate plugin instance that specifies both the Service and the Consumer, through the `service` and `consumer` fields.
type ExitTransformerPlugin struct {
	// Unix epoch when the resource was created.
	CreatedAt *int64 `json:"created_at,omitempty"`
	// Whether the plugin is applied.
	Enabled *bool `default:"true" json:"enabled"`
	// A string representing a UUID (universally unique identifier).
	ID *string `json:"id,omitempty"`
	// A unique string representing a UTF-8 encoded name.
	InstanceName *string                        `default:"null" json:"instance_name"`
	name         string                         `const:"exit-transformer" json:"name"`
	Ordering     *ExitTransformerPluginOrdering `json:"ordering"`
	// A list of partials to be used by the plugin.
	Partials []ExitTransformerPluginPartials `json:"partials"`
	// An optional set of strings associated with the Plugin for grouping and filtering.
	Tags []string `json:"tags"`
	// Unix epoch when the resource was last updated.
	UpdatedAt *int64                      `json:"updated_at,omitempty"`
	Config    ExitTransformerPluginConfig `json:"config"`
	// If set, the plugin will activate only for requests where the specified has been authenticated. (Note that some plugins can not be restricted to consumers this way.). Leave unset for the plugin to activate regardless of the authenticated Consumer.
	Consumer *ExitTransformerPluginConsumer `json:"consumer"`
	// A set of strings representing HTTP protocols.
	Protocols []ExitTransformerPluginProtocols `json:"protocols"`
	// If set, the plugin will only activate when receiving requests via the specified route. Leave unset for the plugin to activate regardless of the route being used.
	Route *ExitTransformerPluginRoute `json:"route"`
	// If set, the plugin will only activate when receiving requests via one of the routes belonging to the specified Service. Leave unset for the plugin to activate regardless of the Service being matched.
	Service *ExitTransformerPluginService `json:"service"`
}

func (e ExitTransformerPlugin) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ExitTransformerPlugin) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *ExitTransformerPlugin) GetCreatedAt() *int64 {
	if e == nil {
		return nil
	}
	return e.CreatedAt
}

func (e *ExitTransformerPlugin) GetEnabled() *bool {
	if e == nil {
		return nil
	}
	return e.Enabled
}

func (e *ExitTransformerPlugin) GetID() *string {
	if e == nil {
		return nil
	}
	return e.ID
}

func (e *ExitTransformerPlugin) GetInstanceName() *string {
	if e == nil {
		return nil
	}
	return e.InstanceName
}

func (e *ExitTransformerPlugin) GetName() string {
	return "exit-transformer"
}

func (e *ExitTransformerPlugin) GetOrdering() *ExitTransformerPluginOrdering {
	if e == nil {
		return nil
	}
	return e.Ordering
}

func (e *ExitTransformerPlugin) GetPartials() []ExitTransformerPluginPartials {
	if e == nil {
		return nil
	}
	return e.Partials
}

func (e *ExitTransformerPlugin) GetTags() []string {
	if e == nil {
		return nil
	}
	return e.Tags
}

func (e *ExitTransformerPlugin) GetUpdatedAt() *int64 {
	if e == nil {
		return nil
	}
	return e.UpdatedAt
}

func (e *ExitTransformerPlugin) GetConfig() ExitTransformerPluginConfig {
	if e == nil {
		return ExitTransformerPluginConfig{}
	}
	return e.Config
}

func (e *ExitTransformerPlugin) GetConsumer() *ExitTransformerPluginConsumer {
	if e == nil {
		return nil
	}
	return e.Consumer
}

func (e *ExitTransformerPlugin) GetProtocols() []ExitTransformerPluginProtocols {
	if e == nil {
		return nil
	}
	return e.Protocols
}

func (e *ExitTransformerPlugin) GetRoute() *ExitTransformerPluginRoute {
	if e == nil {
		return nil
	}
	return e.Route
}

func (e *ExitTransformerPlugin) GetService() *ExitTransformerPluginService {
	if e == nil {
		return nil
	}
	return e.Service
}
