// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"errors"
	"github.com/kong/terraform-provider-konnect/internal/sdk/internal/utils"
)

type InvalidParametersType string

const (
	InvalidParametersTypeInvalidParameterChoiceItem    InvalidParametersType = "InvalidParameterChoiceItem"
	InvalidParametersTypeInvalidParameterDependentItem InvalidParametersType = "InvalidParameterDependentItem"
)

type InvalidParameters struct {
	InvalidParameterChoiceItem    *InvalidParameterChoiceItem
	InvalidParameterDependentItem *InvalidParameterDependentItem

	Type InvalidParametersType
}

func CreateInvalidParametersInvalidParameterChoiceItem(invalidParameterChoiceItem InvalidParameterChoiceItem) InvalidParameters {
	typ := InvalidParametersTypeInvalidParameterChoiceItem

	return InvalidParameters{
		InvalidParameterChoiceItem: &invalidParameterChoiceItem,
		Type:                       typ,
	}
}

func CreateInvalidParametersInvalidParameterDependentItem(invalidParameterDependentItem InvalidParameterDependentItem) InvalidParameters {
	typ := InvalidParametersTypeInvalidParameterDependentItem

	return InvalidParameters{
		InvalidParameterDependentItem: &invalidParameterDependentItem,
		Type:                          typ,
	}
}

func (u *InvalidParameters) UnmarshalJSON(data []byte) error {

	invalidParameterChoiceItem := InvalidParameterChoiceItem{}
	if err := utils.UnmarshalJSON(data, &invalidParameterChoiceItem, "", true, true); err == nil {
		u.InvalidParameterChoiceItem = &invalidParameterChoiceItem
		u.Type = InvalidParametersTypeInvalidParameterChoiceItem
		return nil
	}

	invalidParameterDependentItem := InvalidParameterDependentItem{}
	if err := utils.UnmarshalJSON(data, &invalidParameterDependentItem, "", true, true); err == nil {
		u.InvalidParameterDependentItem = &invalidParameterDependentItem
		u.Type = InvalidParametersTypeInvalidParameterDependentItem
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u InvalidParameters) MarshalJSON() ([]byte, error) {
	if u.InvalidParameterChoiceItem != nil {
		return utils.MarshalJSON(u.InvalidParameterChoiceItem, "", true)
	}

	if u.InvalidParameterDependentItem != nil {
		return utils.MarshalJSON(u.InvalidParameterDependentItem, "", true)
	}

	return nil, errors.New("could not marshal union type: all fields are null")
}
