// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// KonnectCPLegacyNotFoundError - standard error
type KonnectCPLegacyNotFoundError struct {
	Message any `json:"message,omitempty"`
}

func (o *KonnectCPLegacyNotFoundError) GetMessage() any {
	if o == nil {
		return nil
	}
	return o.Message
}
