// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// ListProviderAccountsResponse - A paginated list for a collection of provider accounts.
type ListProviderAccountsResponse struct {
	Data []ProviderAccount `json:"data"`
}

func (l *ListProviderAccountsResponse) GetData() []ProviderAccount {
	if l == nil {
		return []ProviderAccount{}
	}
	return l.Data
}
