// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/kong/terraform-provider-konnect/v3/internal/sdk/internal/utils"
)

type MtlsAuthPluginAfter struct {
	Access []string `json:"access,omitempty"`
}

func (m *MtlsAuthPluginAfter) GetAccess() []string {
	if m == nil {
		return nil
	}
	return m.Access
}

type MtlsAuthPluginBefore struct {
	Access []string `json:"access,omitempty"`
}

func (m *MtlsAuthPluginBefore) GetAccess() []string {
	if m == nil {
		return nil
	}
	return m.Access
}

type MtlsAuthPluginOrdering struct {
	After  *MtlsAuthPluginAfter  `json:"after,omitempty"`
	Before *MtlsAuthPluginBefore `json:"before,omitempty"`
}

func (m *MtlsAuthPluginOrdering) GetAfter() *MtlsAuthPluginAfter {
	if m == nil {
		return nil
	}
	return m.After
}

func (m *MtlsAuthPluginOrdering) GetBefore() *MtlsAuthPluginBefore {
	if m == nil {
		return nil
	}
	return m.Before
}

type MtlsAuthPluginPartials struct {
	// A string representing a UUID (universally unique identifier).
	ID *string `json:"id,omitempty"`
	// A unique string representing a UTF-8 encoded name.
	Name *string `json:"name,omitempty"`
	Path *string `json:"path,omitempty"`
}

func (m *MtlsAuthPluginPartials) GetID() *string {
	if m == nil {
		return nil
	}
	return m.ID
}

func (m *MtlsAuthPluginPartials) GetName() *string {
	if m == nil {
		return nil
	}
	return m.Name
}

func (m *MtlsAuthPluginPartials) GetPath() *string {
	if m == nil {
		return nil
	}
	return m.Path
}

// MtlsAuthPluginAuthenticatedGroupBy - Certificate property to use as the authenticated group. Valid values are `CN` (Common Name) or `DN` (Distinguished Name). Once `skip_consumer_lookup` is applied, any client with a valid certificate can access the Service/API. To restrict usage to only some of the authenticated users, also add the ACL plugin (not covered here) and create allowed or denied groups of users.
type MtlsAuthPluginAuthenticatedGroupBy string

const (
	MtlsAuthPluginAuthenticatedGroupByCn MtlsAuthPluginAuthenticatedGroupBy = "CN"
	MtlsAuthPluginAuthenticatedGroupByDn MtlsAuthPluginAuthenticatedGroupBy = "DN"
)

func (e MtlsAuthPluginAuthenticatedGroupBy) ToPointer() *MtlsAuthPluginAuthenticatedGroupBy {
	return &e
}
func (e *MtlsAuthPluginAuthenticatedGroupBy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "CN":
		fallthrough
	case "DN":
		*e = MtlsAuthPluginAuthenticatedGroupBy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MtlsAuthPluginAuthenticatedGroupBy: %v", v)
	}
}

type MtlsAuthPluginConsumerBy string

const (
	MtlsAuthPluginConsumerByCustomID MtlsAuthPluginConsumerBy = "custom_id"
	MtlsAuthPluginConsumerByUsername MtlsAuthPluginConsumerBy = "username"
)

func (e MtlsAuthPluginConsumerBy) ToPointer() *MtlsAuthPluginConsumerBy {
	return &e
}
func (e *MtlsAuthPluginConsumerBy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "custom_id":
		fallthrough
	case "username":
		*e = MtlsAuthPluginConsumerBy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MtlsAuthPluginConsumerBy: %v", v)
	}
}

// MtlsAuthPluginRevocationCheckMode - Controls client certificate revocation check behavior. If set to `SKIP`, no revocation check is performed. If set to `IGNORE_CA_ERROR`, the plugin respects the revocation status when either OCSP or CRL URL is set, and doesn't fail on network issues. If set to `STRICT`, the plugin only treats the certificate as valid when it's able to verify the revocation status.
type MtlsAuthPluginRevocationCheckMode string

const (
	MtlsAuthPluginRevocationCheckModeIgnoreCaError MtlsAuthPluginRevocationCheckMode = "IGNORE_CA_ERROR"
	MtlsAuthPluginRevocationCheckModeSkip          MtlsAuthPluginRevocationCheckMode = "SKIP"
	MtlsAuthPluginRevocationCheckModeStrict        MtlsAuthPluginRevocationCheckMode = "STRICT"
)

func (e MtlsAuthPluginRevocationCheckMode) ToPointer() *MtlsAuthPluginRevocationCheckMode {
	return &e
}
func (e *MtlsAuthPluginRevocationCheckMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "IGNORE_CA_ERROR":
		fallthrough
	case "SKIP":
		fallthrough
	case "STRICT":
		*e = MtlsAuthPluginRevocationCheckMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MtlsAuthPluginRevocationCheckMode: %v", v)
	}
}

type MtlsAuthPluginConfig struct {
	// Allow certificate verification with only an intermediate certificate. When this is enabled, you don't need to upload the full chain to Kong Certificates.
	AllowPartialChain *bool `default:"false" json:"allow_partial_chain"`
	// An optional string (consumer UUID or username) value to use as an “anonymous” consumer if authentication fails. If empty (default null), the request fails with an authentication failure `4xx`. Note that this value must refer to the consumer `id` or `username` attribute, and **not** its `custom_id`.
	Anonymous *string `default:"null" json:"anonymous"`
	// Certificate property to use as the authenticated group. Valid values are `CN` (Common Name) or `DN` (Distinguished Name). Once `skip_consumer_lookup` is applied, any client with a valid certificate can access the Service/API. To restrict usage to only some of the authenticated users, also add the ACL plugin (not covered here) and create allowed or denied groups of users.
	AuthenticatedGroupBy *MtlsAuthPluginAuthenticatedGroupBy `default:"CN" json:"authenticated_group_by"`
	// List of CA Certificates strings to use as Certificate Authorities (CA) when validating a client certificate. At least one is required but you can specify as many as needed. The value of this array is comprised of primary keys (`id`).
	CaCertificates []string `json:"ca_certificates"`
	// Cache expiry time in seconds.
	CacheTTL *float64 `default:"60" json:"cache_ttl"`
	// The length of time in seconds between refreshes of the revocation check status cache.
	CertCacheTTL *float64 `default:"60000" json:"cert_cache_ttl"`
	// Whether to match the subject name of the client-supplied certificate against consumer's `username` and/or `custom_id` attribute. If set to `[]` (the empty array), then auto-matching is disabled.
	ConsumerBy []MtlsAuthPluginConsumerBy `json:"consumer_by,omitempty"`
	// The UUID or username of the consumer to use when a trusted client certificate is presented but no consumer matches. Note that this value must refer to the consumer `id` or `username` attribute, and **not** its `custom_id`.
	DefaultConsumer *string `default:"null" json:"default_consumer"`
	// A string representing a host name, such as example.com.
	HTTPProxyHost *string `default:"null" json:"http_proxy_host"`
	// An integer representing a port number between 0 and 65535, inclusive.
	HTTPProxyPort *int64 `default:"null" json:"http_proxy_port"`
	// HTTP timeout threshold in milliseconds when communicating with the OCSP server or downloading CRL.
	HTTPTimeout *float64 `default:"30000" json:"http_timeout"`
	// A string representing a host name, such as example.com.
	HTTPSProxyHost *string `default:"null" json:"https_proxy_host"`
	// An integer representing a port number between 0 and 65535, inclusive.
	HTTPSProxyPort *int64 `default:"null" json:"https_proxy_port"`
	// Controls client certificate revocation check behavior. If set to `SKIP`, no revocation check is performed. If set to `IGNORE_CA_ERROR`, the plugin respects the revocation status when either OCSP or CRL URL is set, and doesn't fail on network issues. If set to `STRICT`, the plugin only treats the certificate as valid when it's able to verify the revocation status.
	RevocationCheckMode *MtlsAuthPluginRevocationCheckMode `default:"IGNORE_CA_ERROR" json:"revocation_check_mode"`
	// Sends the distinguished names (DN) of the configured CA list in the TLS handshake message.
	SendCaDn *bool `default:"false" json:"send_ca_dn"`
	// Skip consumer lookup once certificate is trusted against the configured CA list.
	SkipConsumerLookup *bool `default:"false" json:"skip_consumer_lookup"`
	// This option enables verification of the certificate presented by the server of the OCSP responder's URL and by the server of the CRL Distribution Point.
	SslVerify *bool `default:"null" json:"ssl_verify"`
}

func (m MtlsAuthPluginConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MtlsAuthPluginConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MtlsAuthPluginConfig) GetAllowPartialChain() *bool {
	if m == nil {
		return nil
	}
	return m.AllowPartialChain
}

func (m *MtlsAuthPluginConfig) GetAnonymous() *string {
	if m == nil {
		return nil
	}
	return m.Anonymous
}

func (m *MtlsAuthPluginConfig) GetAuthenticatedGroupBy() *MtlsAuthPluginAuthenticatedGroupBy {
	if m == nil {
		return nil
	}
	return m.AuthenticatedGroupBy
}

func (m *MtlsAuthPluginConfig) GetCaCertificates() []string {
	if m == nil {
		return []string{}
	}
	return m.CaCertificates
}

func (m *MtlsAuthPluginConfig) GetCacheTTL() *float64 {
	if m == nil {
		return nil
	}
	return m.CacheTTL
}

func (m *MtlsAuthPluginConfig) GetCertCacheTTL() *float64 {
	if m == nil {
		return nil
	}
	return m.CertCacheTTL
}

func (m *MtlsAuthPluginConfig) GetConsumerBy() []MtlsAuthPluginConsumerBy {
	if m == nil {
		return nil
	}
	return m.ConsumerBy
}

func (m *MtlsAuthPluginConfig) GetDefaultConsumer() *string {
	if m == nil {
		return nil
	}
	return m.DefaultConsumer
}

func (m *MtlsAuthPluginConfig) GetHTTPProxyHost() *string {
	if m == nil {
		return nil
	}
	return m.HTTPProxyHost
}

func (m *MtlsAuthPluginConfig) GetHTTPProxyPort() *int64 {
	if m == nil {
		return nil
	}
	return m.HTTPProxyPort
}

func (m *MtlsAuthPluginConfig) GetHTTPTimeout() *float64 {
	if m == nil {
		return nil
	}
	return m.HTTPTimeout
}

func (m *MtlsAuthPluginConfig) GetHTTPSProxyHost() *string {
	if m == nil {
		return nil
	}
	return m.HTTPSProxyHost
}

func (m *MtlsAuthPluginConfig) GetHTTPSProxyPort() *int64 {
	if m == nil {
		return nil
	}
	return m.HTTPSProxyPort
}

func (m *MtlsAuthPluginConfig) GetRevocationCheckMode() *MtlsAuthPluginRevocationCheckMode {
	if m == nil {
		return nil
	}
	return m.RevocationCheckMode
}

func (m *MtlsAuthPluginConfig) GetSendCaDn() *bool {
	if m == nil {
		return nil
	}
	return m.SendCaDn
}

func (m *MtlsAuthPluginConfig) GetSkipConsumerLookup() *bool {
	if m == nil {
		return nil
	}
	return m.SkipConsumerLookup
}

func (m *MtlsAuthPluginConfig) GetSslVerify() *bool {
	if m == nil {
		return nil
	}
	return m.SslVerify
}

type MtlsAuthPluginProtocols string

const (
	MtlsAuthPluginProtocolsGrpc  MtlsAuthPluginProtocols = "grpc"
	MtlsAuthPluginProtocolsGrpcs MtlsAuthPluginProtocols = "grpcs"
	MtlsAuthPluginProtocolsHTTP  MtlsAuthPluginProtocols = "http"
	MtlsAuthPluginProtocolsHTTPS MtlsAuthPluginProtocols = "https"
)

func (e MtlsAuthPluginProtocols) ToPointer() *MtlsAuthPluginProtocols {
	return &e
}
func (e *MtlsAuthPluginProtocols) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "grpc":
		fallthrough
	case "grpcs":
		fallthrough
	case "http":
		fallthrough
	case "https":
		*e = MtlsAuthPluginProtocols(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MtlsAuthPluginProtocols: %v", v)
	}
}

// MtlsAuthPluginRoute - If set, the plugin will only activate when receiving requests via the specified route. Leave unset for the plugin to activate regardless of the route being used.
type MtlsAuthPluginRoute struct {
	ID *string `json:"id,omitempty"`
}

func (m *MtlsAuthPluginRoute) GetID() *string {
	if m == nil {
		return nil
	}
	return m.ID
}

// MtlsAuthPluginService - If set, the plugin will only activate when receiving requests via one of the routes belonging to the specified Service. Leave unset for the plugin to activate regardless of the Service being matched.
type MtlsAuthPluginService struct {
	ID *string `json:"id,omitempty"`
}

func (m *MtlsAuthPluginService) GetID() *string {
	if m == nil {
		return nil
	}
	return m.ID
}

// MtlsAuthPlugin - A Plugin entity represents a plugin configuration that will be executed during the HTTP request/response lifecycle. It is how you can add functionalities to Services that run behind Kong, like Authentication or Rate Limiting for example. You can find more information about how to install and what values each plugin takes by visiting the [Kong Hub](https://docs.konghq.com/hub/). When adding a Plugin Configuration to a Service, every request made by a client to that Service will run said Plugin. If a Plugin needs to be tuned to different values for some specific Consumers, you can do so by creating a separate plugin instance that specifies both the Service and the Consumer, through the `service` and `consumer` fields.
type MtlsAuthPlugin struct {
	// Unix epoch when the resource was created.
	CreatedAt *int64 `json:"created_at,omitempty"`
	// Whether the plugin is applied.
	Enabled *bool `default:"true" json:"enabled"`
	// A string representing a UUID (universally unique identifier).
	ID *string `json:"id,omitempty"`
	// A unique string representing a UTF-8 encoded name.
	InstanceName *string                 `default:"null" json:"instance_name"`
	name         string                  `const:"mtls-auth" json:"name"`
	Ordering     *MtlsAuthPluginOrdering `json:"ordering"`
	// A list of partials to be used by the plugin.
	Partials []MtlsAuthPluginPartials `json:"partials"`
	// An optional set of strings associated with the Plugin for grouping and filtering.
	Tags []string `json:"tags"`
	// Unix epoch when the resource was last updated.
	UpdatedAt *int64               `json:"updated_at,omitempty"`
	Config    MtlsAuthPluginConfig `json:"config"`
	// A set of strings representing HTTP protocols.
	Protocols []MtlsAuthPluginProtocols `json:"protocols"`
	// If set, the plugin will only activate when receiving requests via the specified route. Leave unset for the plugin to activate regardless of the route being used.
	Route *MtlsAuthPluginRoute `json:"route"`
	// If set, the plugin will only activate when receiving requests via one of the routes belonging to the specified Service. Leave unset for the plugin to activate regardless of the Service being matched.
	Service *MtlsAuthPluginService `json:"service"`
}

func (m MtlsAuthPlugin) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MtlsAuthPlugin) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MtlsAuthPlugin) GetCreatedAt() *int64 {
	if m == nil {
		return nil
	}
	return m.CreatedAt
}

func (m *MtlsAuthPlugin) GetEnabled() *bool {
	if m == nil {
		return nil
	}
	return m.Enabled
}

func (m *MtlsAuthPlugin) GetID() *string {
	if m == nil {
		return nil
	}
	return m.ID
}

func (m *MtlsAuthPlugin) GetInstanceName() *string {
	if m == nil {
		return nil
	}
	return m.InstanceName
}

func (m *MtlsAuthPlugin) GetName() string {
	return "mtls-auth"
}

func (m *MtlsAuthPlugin) GetOrdering() *MtlsAuthPluginOrdering {
	if m == nil {
		return nil
	}
	return m.Ordering
}

func (m *MtlsAuthPlugin) GetPartials() []MtlsAuthPluginPartials {
	if m == nil {
		return nil
	}
	return m.Partials
}

func (m *MtlsAuthPlugin) GetTags() []string {
	if m == nil {
		return nil
	}
	return m.Tags
}

func (m *MtlsAuthPlugin) GetUpdatedAt() *int64 {
	if m == nil {
		return nil
	}
	return m.UpdatedAt
}

func (m *MtlsAuthPlugin) GetConfig() MtlsAuthPluginConfig {
	if m == nil {
		return MtlsAuthPluginConfig{}
	}
	return m.Config
}

func (m *MtlsAuthPlugin) GetProtocols() []MtlsAuthPluginProtocols {
	if m == nil {
		return nil
	}
	return m.Protocols
}

func (m *MtlsAuthPlugin) GetRoute() *MtlsAuthPluginRoute {
	if m == nil {
		return nil
	}
	return m.Route
}

func (m *MtlsAuthPlugin) GetService() *MtlsAuthPluginService {
	if m == nil {
		return nil
	}
	return m.Service
}
