// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// NetworkProviderMetadata - Metadata describing attributes returned by cloud-provider for the network.
type NetworkProviderMetadata struct {
	VpcID     *string  `json:"vpc_id,omitempty"`
	SubnetIds []string `json:"subnet_ids,omitempty"`
}

func (o *NetworkProviderMetadata) GetVpcID() *string {
	if o == nil {
		return nil
	}
	return o.VpcID
}

func (o *NetworkProviderMetadata) GetSubnetIds() []string {
	if o == nil {
		return nil
	}
	return o.SubnetIds
}
