// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// PageVisibilityStatus - Whether a page is publicly accessible to non-authenticated users.
// If not provided, the default_page_visibility value of the portal will be used.
type PageVisibilityStatus string

const (
	PageVisibilityStatusPublic  PageVisibilityStatus = "public"
	PageVisibilityStatusPrivate PageVisibilityStatus = "private"
)

func (e PageVisibilityStatus) ToPointer() *PageVisibilityStatus {
	return &e
}
func (e *PageVisibilityStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "public":
		fallthrough
	case "private":
		*e = PageVisibilityStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PageVisibilityStatus: %v", v)
	}
}
