// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/kong/terraform-provider-konnect/v3/internal/sdk/internal/utils"
)

type PrivateDNSResponseType string

const (
	PrivateDNSResponseTypeAwsPrivateHostedZoneResponse  PrivateDNSResponseType = "AwsPrivateHostedZoneResponse"
	PrivateDNSResponseTypeAwsPrivateDNSResolverResponse PrivateDNSResponseType = "AwsPrivateDnsResolverResponse"
)

// PrivateDNSResponse - Response format for creating a Private DNS.
type PrivateDNSResponse struct {
	AwsPrivateHostedZoneResponse  *AwsPrivateHostedZoneResponse  `queryParam:"inline"`
	AwsPrivateDNSResolverResponse *AwsPrivateDNSResolverResponse `queryParam:"inline"`

	Type PrivateDNSResponseType
}

func CreatePrivateDNSResponseAwsPrivateHostedZoneResponse(awsPrivateHostedZoneResponse AwsPrivateHostedZoneResponse) PrivateDNSResponse {
	typ := PrivateDNSResponseTypeAwsPrivateHostedZoneResponse

	return PrivateDNSResponse{
		AwsPrivateHostedZoneResponse: &awsPrivateHostedZoneResponse,
		Type:                         typ,
	}
}

func CreatePrivateDNSResponseAwsPrivateDNSResolverResponse(awsPrivateDNSResolverResponse AwsPrivateDNSResolverResponse) PrivateDNSResponse {
	typ := PrivateDNSResponseTypeAwsPrivateDNSResolverResponse

	return PrivateDNSResponse{
		AwsPrivateDNSResolverResponse: &awsPrivateDNSResolverResponse,
		Type:                          typ,
	}
}

func (u *PrivateDNSResponse) UnmarshalJSON(data []byte) error {

	var awsPrivateHostedZoneResponse AwsPrivateHostedZoneResponse = AwsPrivateHostedZoneResponse{}
	if err := utils.UnmarshalJSON(data, &awsPrivateHostedZoneResponse, "", true, true); err == nil {
		u.AwsPrivateHostedZoneResponse = &awsPrivateHostedZoneResponse
		u.Type = PrivateDNSResponseTypeAwsPrivateHostedZoneResponse
		return nil
	}

	var awsPrivateDNSResolverResponse AwsPrivateDNSResolverResponse = AwsPrivateDNSResolverResponse{}
	if err := utils.UnmarshalJSON(data, &awsPrivateDNSResolverResponse, "", true, true); err == nil {
		u.AwsPrivateDNSResolverResponse = &awsPrivateDNSResolverResponse
		u.Type = PrivateDNSResponseTypeAwsPrivateDNSResolverResponse
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for PrivateDNSResponse", string(data))
}

func (u PrivateDNSResponse) MarshalJSON() ([]byte, error) {
	if u.AwsPrivateHostedZoneResponse != nil {
		return utils.MarshalJSON(u.AwsPrivateHostedZoneResponse, "", true)
	}

	if u.AwsPrivateDNSResolverResponse != nil {
		return utils.MarshalJSON(u.AwsPrivateDNSResolverResponse, "", true)
	}

	return nil, errors.New("could not marshal union type PrivateDNSResponse: all fields are null")
}
