// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/kong/terraform-provider-konnect/v3/internal/sdk/internal/utils"
)

type ResponseTransformerPluginAfter struct {
	Access []string `json:"access,omitempty"`
}

func (r *ResponseTransformerPluginAfter) GetAccess() []string {
	if r == nil {
		return nil
	}
	return r.Access
}

type ResponseTransformerPluginBefore struct {
	Access []string `json:"access,omitempty"`
}

func (r *ResponseTransformerPluginBefore) GetAccess() []string {
	if r == nil {
		return nil
	}
	return r.Access
}

type ResponseTransformerPluginOrdering struct {
	After  *ResponseTransformerPluginAfter  `json:"after,omitempty"`
	Before *ResponseTransformerPluginBefore `json:"before,omitempty"`
}

func (r *ResponseTransformerPluginOrdering) GetAfter() *ResponseTransformerPluginAfter {
	if r == nil {
		return nil
	}
	return r.After
}

func (r *ResponseTransformerPluginOrdering) GetBefore() *ResponseTransformerPluginBefore {
	if r == nil {
		return nil
	}
	return r.Before
}

type ResponseTransformerPluginPartials struct {
	// A string representing a UUID (universally unique identifier).
	ID *string `json:"id,omitempty"`
	// A unique string representing a UTF-8 encoded name.
	Name *string `json:"name,omitempty"`
	Path *string `json:"path,omitempty"`
}

func (r *ResponseTransformerPluginPartials) GetID() *string {
	if r == nil {
		return nil
	}
	return r.ID
}

func (r *ResponseTransformerPluginPartials) GetName() *string {
	if r == nil {
		return nil
	}
	return r.Name
}

func (r *ResponseTransformerPluginPartials) GetPath() *string {
	if r == nil {
		return nil
	}
	return r.Path
}

type ResponseTransformerPluginJSONTypes string

const (
	ResponseTransformerPluginJSONTypesBoolean ResponseTransformerPluginJSONTypes = "boolean"
	ResponseTransformerPluginJSONTypesNumber  ResponseTransformerPluginJSONTypes = "number"
	ResponseTransformerPluginJSONTypesString  ResponseTransformerPluginJSONTypes = "string"
)

func (e ResponseTransformerPluginJSONTypes) ToPointer() *ResponseTransformerPluginJSONTypes {
	return &e
}
func (e *ResponseTransformerPluginJSONTypes) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "boolean":
		fallthrough
	case "number":
		fallthrough
	case "string":
		*e = ResponseTransformerPluginJSONTypes(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ResponseTransformerPluginJSONTypes: %v", v)
	}
}

type ResponseTransformerPluginAdd struct {
	Headers []string `json:"headers,omitempty"`
	JSON    []string `json:"json,omitempty"`
	// List of JSON type names. Specify the types of the JSON values returned when appending
	// JSON properties. Each string element can be one of: boolean, number, or string.
	JSONTypes []ResponseTransformerPluginJSONTypes `json:"json_types,omitempty"`
}

func (r *ResponseTransformerPluginAdd) GetHeaders() []string {
	if r == nil {
		return nil
	}
	return r.Headers
}

func (r *ResponseTransformerPluginAdd) GetJSON() []string {
	if r == nil {
		return nil
	}
	return r.JSON
}

func (r *ResponseTransformerPluginAdd) GetJSONTypes() []ResponseTransformerPluginJSONTypes {
	if r == nil {
		return nil
	}
	return r.JSONTypes
}

type ResponseTransformerPluginConfigJSONTypes string

const (
	ResponseTransformerPluginConfigJSONTypesBoolean ResponseTransformerPluginConfigJSONTypes = "boolean"
	ResponseTransformerPluginConfigJSONTypesNumber  ResponseTransformerPluginConfigJSONTypes = "number"
	ResponseTransformerPluginConfigJSONTypesString  ResponseTransformerPluginConfigJSONTypes = "string"
)

func (e ResponseTransformerPluginConfigJSONTypes) ToPointer() *ResponseTransformerPluginConfigJSONTypes {
	return &e
}
func (e *ResponseTransformerPluginConfigJSONTypes) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "boolean":
		fallthrough
	case "number":
		fallthrough
	case "string":
		*e = ResponseTransformerPluginConfigJSONTypes(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ResponseTransformerPluginConfigJSONTypes: %v", v)
	}
}

type ResponseTransformerPluginAppend struct {
	Headers []string `json:"headers,omitempty"`
	JSON    []string `json:"json,omitempty"`
	// List of JSON type names. Specify the types of the JSON values returned when appending
	// JSON properties. Each string element can be one of: boolean, number, or string.
	JSONTypes []ResponseTransformerPluginConfigJSONTypes `json:"json_types,omitempty"`
}

func (r *ResponseTransformerPluginAppend) GetHeaders() []string {
	if r == nil {
		return nil
	}
	return r.Headers
}

func (r *ResponseTransformerPluginAppend) GetJSON() []string {
	if r == nil {
		return nil
	}
	return r.JSON
}

func (r *ResponseTransformerPluginAppend) GetJSONTypes() []ResponseTransformerPluginConfigJSONTypes {
	if r == nil {
		return nil
	}
	return r.JSONTypes
}

type ResponseTransformerPluginRemove struct {
	Headers []string `json:"headers,omitempty"`
	JSON    []string `json:"json,omitempty"`
}

func (r *ResponseTransformerPluginRemove) GetHeaders() []string {
	if r == nil {
		return nil
	}
	return r.Headers
}

func (r *ResponseTransformerPluginRemove) GetJSON() []string {
	if r == nil {
		return nil
	}
	return r.JSON
}

type ResponseTransformerPluginRename struct {
	Headers []string `json:"headers,omitempty"`
	JSON    []string `json:"json,omitempty"`
}

func (r *ResponseTransformerPluginRename) GetHeaders() []string {
	if r == nil {
		return nil
	}
	return r.Headers
}

func (r *ResponseTransformerPluginRename) GetJSON() []string {
	if r == nil {
		return nil
	}
	return r.JSON
}

type ResponseTransformerPluginConfigReplaceJSONTypes string

const (
	ResponseTransformerPluginConfigReplaceJSONTypesBoolean ResponseTransformerPluginConfigReplaceJSONTypes = "boolean"
	ResponseTransformerPluginConfigReplaceJSONTypesNumber  ResponseTransformerPluginConfigReplaceJSONTypes = "number"
	ResponseTransformerPluginConfigReplaceJSONTypesString  ResponseTransformerPluginConfigReplaceJSONTypes = "string"
)

func (e ResponseTransformerPluginConfigReplaceJSONTypes) ToPointer() *ResponseTransformerPluginConfigReplaceJSONTypes {
	return &e
}
func (e *ResponseTransformerPluginConfigReplaceJSONTypes) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "boolean":
		fallthrough
	case "number":
		fallthrough
	case "string":
		*e = ResponseTransformerPluginConfigReplaceJSONTypes(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ResponseTransformerPluginConfigReplaceJSONTypes: %v", v)
	}
}

type ResponseTransformerPluginReplace struct {
	Headers []string `json:"headers,omitempty"`
	JSON    []string `json:"json,omitempty"`
	// List of JSON type names. Specify the types of the JSON values returned when appending
	// JSON properties. Each string element can be one of: boolean, number, or string.
	JSONTypes []ResponseTransformerPluginConfigReplaceJSONTypes `json:"json_types,omitempty"`
}

func (r *ResponseTransformerPluginReplace) GetHeaders() []string {
	if r == nil {
		return nil
	}
	return r.Headers
}

func (r *ResponseTransformerPluginReplace) GetJSON() []string {
	if r == nil {
		return nil
	}
	return r.JSON
}

func (r *ResponseTransformerPluginReplace) GetJSONTypes() []ResponseTransformerPluginConfigReplaceJSONTypes {
	if r == nil {
		return nil
	}
	return r.JSONTypes
}

type ResponseTransformerPluginConfig struct {
	Add     *ResponseTransformerPluginAdd     `json:"add,omitempty"`
	Append  *ResponseTransformerPluginAppend  `json:"append,omitempty"`
	Remove  *ResponseTransformerPluginRemove  `json:"remove,omitempty"`
	Rename  *ResponseTransformerPluginRename  `json:"rename,omitempty"`
	Replace *ResponseTransformerPluginReplace `json:"replace,omitempty"`
}

func (r *ResponseTransformerPluginConfig) GetAdd() *ResponseTransformerPluginAdd {
	if r == nil {
		return nil
	}
	return r.Add
}

func (r *ResponseTransformerPluginConfig) GetAppend() *ResponseTransformerPluginAppend {
	if r == nil {
		return nil
	}
	return r.Append
}

func (r *ResponseTransformerPluginConfig) GetRemove() *ResponseTransformerPluginRemove {
	if r == nil {
		return nil
	}
	return r.Remove
}

func (r *ResponseTransformerPluginConfig) GetRename() *ResponseTransformerPluginRename {
	if r == nil {
		return nil
	}
	return r.Rename
}

func (r *ResponseTransformerPluginConfig) GetReplace() *ResponseTransformerPluginReplace {
	if r == nil {
		return nil
	}
	return r.Replace
}

// ResponseTransformerPluginConsumer - If set, the plugin will activate only for requests where the specified has been authenticated. (Note that some plugins can not be restricted to consumers this way.). Leave unset for the plugin to activate regardless of the authenticated Consumer.
type ResponseTransformerPluginConsumer struct {
	ID *string `json:"id,omitempty"`
}

func (r *ResponseTransformerPluginConsumer) GetID() *string {
	if r == nil {
		return nil
	}
	return r.ID
}

// ResponseTransformerPluginConsumerGroup - If set, the plugin will activate only for requests where the specified consumer group has been authenticated. (Note that some plugins can not be restricted to consumers groups this way.). Leave unset for the plugin to activate regardless of the authenticated Consumer Groups
type ResponseTransformerPluginConsumerGroup struct {
	ID *string `json:"id,omitempty"`
}

func (r *ResponseTransformerPluginConsumerGroup) GetID() *string {
	if r == nil {
		return nil
	}
	return r.ID
}

type ResponseTransformerPluginProtocols string

const (
	ResponseTransformerPluginProtocolsGrpc  ResponseTransformerPluginProtocols = "grpc"
	ResponseTransformerPluginProtocolsGrpcs ResponseTransformerPluginProtocols = "grpcs"
	ResponseTransformerPluginProtocolsHTTP  ResponseTransformerPluginProtocols = "http"
	ResponseTransformerPluginProtocolsHTTPS ResponseTransformerPluginProtocols = "https"
)

func (e ResponseTransformerPluginProtocols) ToPointer() *ResponseTransformerPluginProtocols {
	return &e
}
func (e *ResponseTransformerPluginProtocols) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "grpc":
		fallthrough
	case "grpcs":
		fallthrough
	case "http":
		fallthrough
	case "https":
		*e = ResponseTransformerPluginProtocols(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ResponseTransformerPluginProtocols: %v", v)
	}
}

// ResponseTransformerPluginRoute - If set, the plugin will only activate when receiving requests via the specified route. Leave unset for the plugin to activate regardless of the route being used.
type ResponseTransformerPluginRoute struct {
	ID *string `json:"id,omitempty"`
}

func (r *ResponseTransformerPluginRoute) GetID() *string {
	if r == nil {
		return nil
	}
	return r.ID
}

// ResponseTransformerPluginService - If set, the plugin will only activate when receiving requests via one of the routes belonging to the specified Service. Leave unset for the plugin to activate regardless of the Service being matched.
type ResponseTransformerPluginService struct {
	ID *string `json:"id,omitempty"`
}

func (r *ResponseTransformerPluginService) GetID() *string {
	if r == nil {
		return nil
	}
	return r.ID
}

// ResponseTransformerPlugin - A Plugin entity represents a plugin configuration that will be executed during the HTTP request/response lifecycle. It is how you can add functionalities to Services that run behind Kong, like Authentication or Rate Limiting for example. You can find more information about how to install and what values each plugin takes by visiting the [Kong Hub](https://docs.konghq.com/hub/). When adding a Plugin Configuration to a Service, every request made by a client to that Service will run said Plugin. If a Plugin needs to be tuned to different values for some specific Consumers, you can do so by creating a separate plugin instance that specifies both the Service and the Consumer, through the `service` and `consumer` fields.
type ResponseTransformerPlugin struct {
	// Unix epoch when the resource was created.
	CreatedAt *int64 `json:"created_at,omitempty"`
	// Whether the plugin is applied.
	Enabled *bool `default:"true" json:"enabled"`
	// A string representing a UUID (universally unique identifier).
	ID *string `json:"id,omitempty"`
	// A unique string representing a UTF-8 encoded name.
	InstanceName *string                            `default:"null" json:"instance_name"`
	name         string                             `const:"response-transformer" json:"name"`
	Ordering     *ResponseTransformerPluginOrdering `json:"ordering"`
	// A list of partials to be used by the plugin.
	Partials []ResponseTransformerPluginPartials `json:"partials"`
	// An optional set of strings associated with the Plugin for grouping and filtering.
	Tags []string `json:"tags"`
	// Unix epoch when the resource was last updated.
	UpdatedAt *int64                           `json:"updated_at,omitempty"`
	Config    *ResponseTransformerPluginConfig `json:"config"`
	// If set, the plugin will activate only for requests where the specified has been authenticated. (Note that some plugins can not be restricted to consumers this way.). Leave unset for the plugin to activate regardless of the authenticated Consumer.
	Consumer *ResponseTransformerPluginConsumer `json:"consumer"`
	// If set, the plugin will activate only for requests where the specified consumer group has been authenticated. (Note that some plugins can not be restricted to consumers groups this way.). Leave unset for the plugin to activate regardless of the authenticated Consumer Groups
	ConsumerGroup *ResponseTransformerPluginConsumerGroup `json:"consumer_group"`
	// A set of strings representing HTTP protocols.
	Protocols []ResponseTransformerPluginProtocols `json:"protocols"`
	// If set, the plugin will only activate when receiving requests via the specified route. Leave unset for the plugin to activate regardless of the route being used.
	Route *ResponseTransformerPluginRoute `json:"route"`
	// If set, the plugin will only activate when receiving requests via one of the routes belonging to the specified Service. Leave unset for the plugin to activate regardless of the Service being matched.
	Service *ResponseTransformerPluginService `json:"service"`
}

func (r ResponseTransformerPlugin) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ResponseTransformerPlugin) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, []string{"name"}); err != nil {
		return err
	}
	return nil
}

func (r *ResponseTransformerPlugin) GetCreatedAt() *int64 {
	if r == nil {
		return nil
	}
	return r.CreatedAt
}

func (r *ResponseTransformerPlugin) GetEnabled() *bool {
	if r == nil {
		return nil
	}
	return r.Enabled
}

func (r *ResponseTransformerPlugin) GetID() *string {
	if r == nil {
		return nil
	}
	return r.ID
}

func (r *ResponseTransformerPlugin) GetInstanceName() *string {
	if r == nil {
		return nil
	}
	return r.InstanceName
}

func (r *ResponseTransformerPlugin) GetName() string {
	return "response-transformer"
}

func (r *ResponseTransformerPlugin) GetOrdering() *ResponseTransformerPluginOrdering {
	if r == nil {
		return nil
	}
	return r.Ordering
}

func (r *ResponseTransformerPlugin) GetPartials() []ResponseTransformerPluginPartials {
	if r == nil {
		return nil
	}
	return r.Partials
}

func (r *ResponseTransformerPlugin) GetTags() []string {
	if r == nil {
		return nil
	}
	return r.Tags
}

func (r *ResponseTransformerPlugin) GetUpdatedAt() *int64 {
	if r == nil {
		return nil
	}
	return r.UpdatedAt
}

func (r *ResponseTransformerPlugin) GetConfig() *ResponseTransformerPluginConfig {
	if r == nil {
		return nil
	}
	return r.Config
}

func (r *ResponseTransformerPlugin) GetConsumer() *ResponseTransformerPluginConsumer {
	if r == nil {
		return nil
	}
	return r.Consumer
}

func (r *ResponseTransformerPlugin) GetConsumerGroup() *ResponseTransformerPluginConsumerGroup {
	if r == nil {
		return nil
	}
	return r.ConsumerGroup
}

func (r *ResponseTransformerPlugin) GetProtocols() []ResponseTransformerPluginProtocols {
	if r == nil {
		return nil
	}
	return r.Protocols
}

func (r *ResponseTransformerPlugin) GetRoute() *ResponseTransformerPluginRoute {
	if r == nil {
		return nil
	}
	return r.Route
}

func (r *ResponseTransformerPlugin) GetService() *ResponseTransformerPluginService {
	if r == nil {
		return nil
	}
	return r.Service
}
