// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/kong/terraform-provider-konnect/v3/internal/sdk/internal/utils"
)

// SchemaRegistryConfluentSensitiveDataAware - A Confluent schema registry.
type SchemaRegistryConfluentSensitiveDataAware struct {
	// The unique name of the schema registry.
	Name string `json:"name"`
	// A human-readable description.
	Description *string `json:"description,omitempty"`
	// The type of the schema registry.
	type_ string `const:"confluent" json:"type"`
	// The configuration of [Confluent Schema Registry](https://github.com/confluentinc/schema-registry)
	//
	Config SchemaRegistryConfluentConfigSensitiveDataAware `json:"config"`
	// Labels store metadata of an entity that can be used for filtering an entity list or for searching across entity types.
	//
	// Keys must be of length 1-63 characters, and cannot start with "kong", "konnect", "mesh", "kic", or "_".
	//
	Labels map[string]*string `json:"labels,omitempty"`
}

func (s SchemaRegistryConfluentSensitiveDataAware) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SchemaRegistryConfluentSensitiveDataAware) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SchemaRegistryConfluentSensitiveDataAware) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *SchemaRegistryConfluentSensitiveDataAware) GetDescription() *string {
	if s == nil {
		return nil
	}
	return s.Description
}

func (s *SchemaRegistryConfluentSensitiveDataAware) GetType() string {
	return "confluent"
}

func (s *SchemaRegistryConfluentSensitiveDataAware) GetConfig() SchemaRegistryConfluentConfigSensitiveDataAware {
	if s == nil {
		return SchemaRegistryConfluentConfigSensitiveDataAware{}
	}
	return s.Config
}

func (s *SchemaRegistryConfluentSensitiveDataAware) GetLabels() map[string]*string {
	if s == nil {
		return nil
	}
	return s.Labels
}
