// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// UpdateDcrConfigHTTPInRequest - Payload to update an HTTP DCR provider.
type UpdateDcrConfigHTTPInRequest struct {
	// The base URL of the DCR server. This is the URL that will be used to make the HTTP requests from Konnect to the DCR provider.
	// This URL must be accessible from the Konnect service.
	//
	DcrBaseURL *string `json:"dcr_base_url,omitempty"`
	// This is the API Key that will be sent with each HTTP request to the custom DCR server. It can be
	// verified on the server to ensure that incoming requests are coming from Konnect.
	//
	APIKey *string `json:"api_key,omitempty"`
	// This flag disables all the event-hooks on the application flow for the DCR provider.
	DisableEventHooks *bool `json:"disable_event_hooks,omitempty"`
	// This flag disable the refresh-secret endpoint on the application flow for the DCR provider.
	DisableRefreshSecret *bool `json:"disable_refresh_secret,omitempty"`
}

func (o *UpdateDcrConfigHTTPInRequest) GetDcrBaseURL() *string {
	if o == nil {
		return nil
	}
	return o.DcrBaseURL
}

func (o *UpdateDcrConfigHTTPInRequest) GetAPIKey() *string {
	if o == nil {
		return nil
	}
	return o.APIKey
}

func (o *UpdateDcrConfigHTTPInRequest) GetDisableEventHooks() *bool {
	if o == nil {
		return nil
	}
	return o.DisableEventHooks
}

func (o *UpdateDcrConfigHTTPInRequest) GetDisableRefreshSecret() *bool {
	if o == nil {
		return nil
	}
	return o.DisableRefreshSecret
}
