// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/kong/terraform-provider-konnect/v3/internal/sdk/internal/utils"
)

type XMLThreatProtectionPluginAfter struct {
	Access []string `json:"access,omitempty"`
}

func (x *XMLThreatProtectionPluginAfter) GetAccess() []string {
	if x == nil {
		return nil
	}
	return x.Access
}

type XMLThreatProtectionPluginBefore struct {
	Access []string `json:"access,omitempty"`
}

func (x *XMLThreatProtectionPluginBefore) GetAccess() []string {
	if x == nil {
		return nil
	}
	return x.Access
}

type XMLThreatProtectionPluginOrdering struct {
	After  *XMLThreatProtectionPluginAfter  `json:"after,omitempty"`
	Before *XMLThreatProtectionPluginBefore `json:"before,omitempty"`
}

func (x *XMLThreatProtectionPluginOrdering) GetAfter() *XMLThreatProtectionPluginAfter {
	if x == nil {
		return nil
	}
	return x.After
}

func (x *XMLThreatProtectionPluginOrdering) GetBefore() *XMLThreatProtectionPluginBefore {
	if x == nil {
		return nil
	}
	return x.Before
}

type XMLThreatProtectionPluginPartials struct {
	// A string representing a UUID (universally unique identifier).
	ID *string `json:"id,omitempty"`
	// A unique string representing a UTF-8 encoded name.
	Name *string `json:"name,omitempty"`
	Path *string `json:"path,omitempty"`
}

func (x *XMLThreatProtectionPluginPartials) GetID() *string {
	if x == nil {
		return nil
	}
	return x.ID
}

func (x *XMLThreatProtectionPluginPartials) GetName() *string {
	if x == nil {
		return nil
	}
	return x.Name
}

func (x *XMLThreatProtectionPluginPartials) GetPath() *string {
	if x == nil {
		return nil
	}
	return x.Path
}

type XMLThreatProtectionPluginConfig struct {
	// Indicates whether an XML Document Type Definition (DTD) section is allowed.
	AllowDtd *bool `default:"false" json:"allow_dtd"`
	// A list of Content-Type values with payloads that are allowed, but aren't validated.
	AllowedContentTypes []string `json:"allowed_content_types,omitempty"`
	// Maximum size of the attribute value.
	Attribute *int64 `default:"1048576" json:"attribute"`
	// Sets the maximum allowed amplification. This protects against the Billion Laughs Attack.
	BlaMaxAmplification *float64 `default:"100" json:"bla_max_amplification"`
	// Sets the threshold after which the protection starts. This protects against the Billion Laughs Attack.
	BlaThreshold *int64 `default:"8388608" json:"bla_threshold"`
	// Maximum size of the unparsed buffer (see below).
	Buffer *int64 `default:"1048576" json:"buffer"`
	// A list of Content-Type values with payloads that must be validated.
	CheckedContentTypes []string `json:"checked_content_types,omitempty"`
	// Maximum size of comments.
	Comment *int64 `default:"1024" json:"comment"`
	// Maximum size of the entire document.
	Document *int64 `default:"10485760" json:"document"`
	// Maximum size of entity values in EntityDecl.
	Entity *int64 `default:"1024" json:"entity"`
	// Maximum size of entity names in EntityDecl.
	Entityname *int64 `default:"1024" json:"entityname"`
	// Maximum size of systemId, publicId, or notationName in EntityDecl.
	Entityproperty *int64 `default:"1024" json:"entityproperty"`
	// Maximum size of the localname. This applies to tags and attributes.
	Localname *int64 `default:"1024" json:"localname"`
	// Maximum number of attributes allowed on a tag, including default ones. Note: If namespace-aware parsing is disabled, then the namespaces definitions are counted as attributes.
	MaxAttributes *int64 `default:"100" json:"max_attributes"`
	// Maximum number of children allowed (Element, Text, Comment, ProcessingInstruction, CDATASection). Note: Adjacent text and CDATA sections are counted as one. For example, text-cdata-text-cdata is one child.
	MaxChildren *int64 `default:"100" json:"max_children"`
	// Maximum depth of tags. Child elements such as Text or Comments are not counted as another level.
	MaxDepth *int64 `default:"50" json:"max_depth"`
	// Maximum number of namespaces defined on a tag. This value is required if parsing is namespace-aware.
	MaxNamespaces *int64 `default:"20" json:"max_namespaces"`
	// If not parsing namespace aware, all prefixes and namespace attributes will be counted as regular attributes and element names, and validated as such.
	NamespaceAware *bool `default:"true" json:"namespace_aware"`
	// Maximum size of the namespace URI. This value is required if parsing is namespace-aware.
	Namespaceuri *int64 `default:"1024" json:"namespaceuri"`
	// Maximum size of processing instruction data.
	Pidata *int64 `default:"1024" json:"pidata"`
	// Maximum size of processing instruction targets.
	Pitarget *int64 `default:"1024" json:"pitarget"`
	// Maximum size of the prefix. This applies to tags and attributes. This value is required if parsing is namespace-aware.
	Prefix *int64 `default:"1024" json:"prefix"`
	// Maximum text inside tags (counted over all adjacent text/CDATA elements combined).
	Text *int64 `default:"1048576" json:"text"`
}

func (x XMLThreatProtectionPluginConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(x, "", false)
}

func (x *XMLThreatProtectionPluginConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &x, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (x *XMLThreatProtectionPluginConfig) GetAllowDtd() *bool {
	if x == nil {
		return nil
	}
	return x.AllowDtd
}

func (x *XMLThreatProtectionPluginConfig) GetAllowedContentTypes() []string {
	if x == nil {
		return nil
	}
	return x.AllowedContentTypes
}

func (x *XMLThreatProtectionPluginConfig) GetAttribute() *int64 {
	if x == nil {
		return nil
	}
	return x.Attribute
}

func (x *XMLThreatProtectionPluginConfig) GetBlaMaxAmplification() *float64 {
	if x == nil {
		return nil
	}
	return x.BlaMaxAmplification
}

func (x *XMLThreatProtectionPluginConfig) GetBlaThreshold() *int64 {
	if x == nil {
		return nil
	}
	return x.BlaThreshold
}

func (x *XMLThreatProtectionPluginConfig) GetBuffer() *int64 {
	if x == nil {
		return nil
	}
	return x.Buffer
}

func (x *XMLThreatProtectionPluginConfig) GetCheckedContentTypes() []string {
	if x == nil {
		return nil
	}
	return x.CheckedContentTypes
}

func (x *XMLThreatProtectionPluginConfig) GetComment() *int64 {
	if x == nil {
		return nil
	}
	return x.Comment
}

func (x *XMLThreatProtectionPluginConfig) GetDocument() *int64 {
	if x == nil {
		return nil
	}
	return x.Document
}

func (x *XMLThreatProtectionPluginConfig) GetEntity() *int64 {
	if x == nil {
		return nil
	}
	return x.Entity
}

func (x *XMLThreatProtectionPluginConfig) GetEntityname() *int64 {
	if x == nil {
		return nil
	}
	return x.Entityname
}

func (x *XMLThreatProtectionPluginConfig) GetEntityproperty() *int64 {
	if x == nil {
		return nil
	}
	return x.Entityproperty
}

func (x *XMLThreatProtectionPluginConfig) GetLocalname() *int64 {
	if x == nil {
		return nil
	}
	return x.Localname
}

func (x *XMLThreatProtectionPluginConfig) GetMaxAttributes() *int64 {
	if x == nil {
		return nil
	}
	return x.MaxAttributes
}

func (x *XMLThreatProtectionPluginConfig) GetMaxChildren() *int64 {
	if x == nil {
		return nil
	}
	return x.MaxChildren
}

func (x *XMLThreatProtectionPluginConfig) GetMaxDepth() *int64 {
	if x == nil {
		return nil
	}
	return x.MaxDepth
}

func (x *XMLThreatProtectionPluginConfig) GetMaxNamespaces() *int64 {
	if x == nil {
		return nil
	}
	return x.MaxNamespaces
}

func (x *XMLThreatProtectionPluginConfig) GetNamespaceAware() *bool {
	if x == nil {
		return nil
	}
	return x.NamespaceAware
}

func (x *XMLThreatProtectionPluginConfig) GetNamespaceuri() *int64 {
	if x == nil {
		return nil
	}
	return x.Namespaceuri
}

func (x *XMLThreatProtectionPluginConfig) GetPidata() *int64 {
	if x == nil {
		return nil
	}
	return x.Pidata
}

func (x *XMLThreatProtectionPluginConfig) GetPitarget() *int64 {
	if x == nil {
		return nil
	}
	return x.Pitarget
}

func (x *XMLThreatProtectionPluginConfig) GetPrefix() *int64 {
	if x == nil {
		return nil
	}
	return x.Prefix
}

func (x *XMLThreatProtectionPluginConfig) GetText() *int64 {
	if x == nil {
		return nil
	}
	return x.Text
}

// XMLThreatProtectionPluginConsumer - If set, the plugin will activate only for requests where the specified has been authenticated. (Note that some plugins can not be restricted to consumers this way.). Leave unset for the plugin to activate regardless of the authenticated Consumer.
type XMLThreatProtectionPluginConsumer struct {
	ID *string `json:"id,omitempty"`
}

func (x *XMLThreatProtectionPluginConsumer) GetID() *string {
	if x == nil {
		return nil
	}
	return x.ID
}

type XMLThreatProtectionPluginProtocols string

const (
	XMLThreatProtectionPluginProtocolsGrpc  XMLThreatProtectionPluginProtocols = "grpc"
	XMLThreatProtectionPluginProtocolsGrpcs XMLThreatProtectionPluginProtocols = "grpcs"
	XMLThreatProtectionPluginProtocolsHTTP  XMLThreatProtectionPluginProtocols = "http"
	XMLThreatProtectionPluginProtocolsHTTPS XMLThreatProtectionPluginProtocols = "https"
)

func (e XMLThreatProtectionPluginProtocols) ToPointer() *XMLThreatProtectionPluginProtocols {
	return &e
}
func (e *XMLThreatProtectionPluginProtocols) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "grpc":
		fallthrough
	case "grpcs":
		fallthrough
	case "http":
		fallthrough
	case "https":
		*e = XMLThreatProtectionPluginProtocols(v)
		return nil
	default:
		return fmt.Errorf("invalid value for XMLThreatProtectionPluginProtocols: %v", v)
	}
}

// XMLThreatProtectionPluginRoute - If set, the plugin will only activate when receiving requests via the specified route. Leave unset for the plugin to activate regardless of the route being used.
type XMLThreatProtectionPluginRoute struct {
	ID *string `json:"id,omitempty"`
}

func (x *XMLThreatProtectionPluginRoute) GetID() *string {
	if x == nil {
		return nil
	}
	return x.ID
}

// XMLThreatProtectionPluginService - If set, the plugin will only activate when receiving requests via one of the routes belonging to the specified Service. Leave unset for the plugin to activate regardless of the Service being matched.
type XMLThreatProtectionPluginService struct {
	ID *string `json:"id,omitempty"`
}

func (x *XMLThreatProtectionPluginService) GetID() *string {
	if x == nil {
		return nil
	}
	return x.ID
}

// XMLThreatProtectionPlugin - A Plugin entity represents a plugin configuration that will be executed during the HTTP request/response lifecycle. It is how you can add functionalities to Services that run behind Kong, like Authentication or Rate Limiting for example. You can find more information about how to install and what values each plugin takes by visiting the [Kong Hub](https://docs.konghq.com/hub/). When adding a Plugin Configuration to a Service, every request made by a client to that Service will run said Plugin. If a Plugin needs to be tuned to different values for some specific Consumers, you can do so by creating a separate plugin instance that specifies both the Service and the Consumer, through the `service` and `consumer` fields.
type XMLThreatProtectionPlugin struct {
	// Unix epoch when the resource was created.
	CreatedAt *int64 `json:"created_at,omitempty"`
	// Whether the plugin is applied.
	Enabled *bool `default:"true" json:"enabled"`
	// A string representing a UUID (universally unique identifier).
	ID *string `json:"id,omitempty"`
	// A unique string representing a UTF-8 encoded name.
	InstanceName *string                            `default:"null" json:"instance_name"`
	name         string                             `const:"xml-threat-protection" json:"name"`
	Ordering     *XMLThreatProtectionPluginOrdering `json:"ordering"`
	// A list of partials to be used by the plugin.
	Partials []XMLThreatProtectionPluginPartials `json:"partials"`
	// An optional set of strings associated with the Plugin for grouping and filtering.
	Tags []string `json:"tags"`
	// Unix epoch when the resource was last updated.
	UpdatedAt *int64                           `json:"updated_at,omitempty"`
	Config    *XMLThreatProtectionPluginConfig `json:"config"`
	// If set, the plugin will activate only for requests where the specified has been authenticated. (Note that some plugins can not be restricted to consumers this way.). Leave unset for the plugin to activate regardless of the authenticated Consumer.
	Consumer *XMLThreatProtectionPluginConsumer `json:"consumer"`
	// A set of strings representing HTTP protocols.
	Protocols []XMLThreatProtectionPluginProtocols `json:"protocols"`
	// If set, the plugin will only activate when receiving requests via the specified route. Leave unset for the plugin to activate regardless of the route being used.
	Route *XMLThreatProtectionPluginRoute `json:"route"`
	// If set, the plugin will only activate when receiving requests via one of the routes belonging to the specified Service. Leave unset for the plugin to activate regardless of the Service being matched.
	Service *XMLThreatProtectionPluginService `json:"service"`
}

func (x XMLThreatProtectionPlugin) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(x, "", false)
}

func (x *XMLThreatProtectionPlugin) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &x, "", false, []string{"name", "ordering", "partials", "tags", "config", "consumer", "route", "service"}); err != nil {
		return err
	}
	return nil
}

func (x *XMLThreatProtectionPlugin) GetCreatedAt() *int64 {
	if x == nil {
		return nil
	}
	return x.CreatedAt
}

func (x *XMLThreatProtectionPlugin) GetEnabled() *bool {
	if x == nil {
		return nil
	}
	return x.Enabled
}

func (x *XMLThreatProtectionPlugin) GetID() *string {
	if x == nil {
		return nil
	}
	return x.ID
}

func (x *XMLThreatProtectionPlugin) GetInstanceName() *string {
	if x == nil {
		return nil
	}
	return x.InstanceName
}

func (x *XMLThreatProtectionPlugin) GetName() string {
	return "xml-threat-protection"
}

func (x *XMLThreatProtectionPlugin) GetOrdering() *XMLThreatProtectionPluginOrdering {
	if x == nil {
		return nil
	}
	return x.Ordering
}

func (x *XMLThreatProtectionPlugin) GetPartials() []XMLThreatProtectionPluginPartials {
	if x == nil {
		return nil
	}
	return x.Partials
}

func (x *XMLThreatProtectionPlugin) GetTags() []string {
	if x == nil {
		return nil
	}
	return x.Tags
}

func (x *XMLThreatProtectionPlugin) GetUpdatedAt() *int64 {
	if x == nil {
		return nil
	}
	return x.UpdatedAt
}

func (x *XMLThreatProtectionPlugin) GetConfig() *XMLThreatProtectionPluginConfig {
	if x == nil {
		return nil
	}
	return x.Config
}

func (x *XMLThreatProtectionPlugin) GetConsumer() *XMLThreatProtectionPluginConsumer {
	if x == nil {
		return nil
	}
	return x.Consumer
}

func (x *XMLThreatProtectionPlugin) GetProtocols() []XMLThreatProtectionPluginProtocols {
	if x == nil {
		return nil
	}
	return x.Protocols
}

func (x *XMLThreatProtectionPlugin) GetRoute() *XMLThreatProtectionPluginRoute {
	if x == nil {
		return nil
	}
	return x.Route
}

func (x *XMLThreatProtectionPlugin) GetService() *XMLThreatProtectionPluginService {
	if x == nil {
		return nil
	}
	return x.Service
}
