openapi: 3.0.0
info:
  title: Portal Search API
  version: 2.0.0
  description: N/A (this description is removed during bundling)
  contact:
    name: Kong
    url: 'https://cloud.konghq.com'
paths:
  /api/v2/search/{indices}:
    get:
      summary: Search Portal Entities
      operationId: search-portal-entities
      description: Returns paginated search results from the specified entities with the given search parameters.
      responses:
        '200':
          $ref: '#/components/responses/SearchResponse'
        '400':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/BadRequest'
        '401':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/Unauthorized'
      parameters:
        - $ref: '#/components/parameters/SearchIndices'
        - $ref: '#/components/parameters/SearchQuery'
        - $ref: '#/components/parameters/SearchJoin'
        - $ref: '../../../../common/definitions/metadatas.yaml#/components/parameters/PageSize'
        - $ref: '../../../../common/definitions/metadatas.yaml#/components/parameters/PageNumber'
      tags:
        - search
      security:
        - portalAccessToken: []
        - {}
components:
  securitySchemes:
    portalAccessToken:
      $ref: '../../../../common/definitions/security.yaml#/components/securitySchemes/portalAccessToken'
  parameters:
    SearchQuery:
      name: q
      description: Determines how to filter search results
      required: false
      in: query
      schema:
        $ref: '#/components/schemas/SearchQueryParameters'
    SearchJoin:
      name: join
      description: Determines which sub-entities to include in search results
      required: false
      in: query
      schema:
        $ref: '#/components/schemas/SearchJoinParameters'
    SearchIndices:
      name: indices
      description: Determines which entity sets to search
      required: true
      in: path
      schema:
        $ref: '#/components/schemas/SearchIndicesParameters'
  responses:
    SearchResponse:
      description: Search Results
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SearchResults'
          examples:
            Search Response Example:
              $ref: '#/components/examples/SearchResponseExample'
  schemas:
    SearchResults:
      title: 'SearchResults'
      type: object
      required:
        - data
        - meta
      properties:
        meta:
          $ref: '../../../../common/definitions/metadatas.yaml#/components/schemas/PaginatedMeta'
        data:
          type: array
          description: The paginated results that matched the search query
          items:
            type: object
            additionalProperties: false
            properties:
              index:
                $ref: '#/components/schemas/SearchIndicesParameters'
              source:
                $ref: '#/components/schemas/ProductCatalogIndexSource'
            required:
              - index
              - source
    ProductCatalogIndexSource:
      title: 'ProductCatalogIndexSource'
      type: object
      additionalProperties: false
      required:
        - id
        - created_at
        - updated_at
        - name
        - has_documentation
      properties:
        id:
          $ref: '../../../../common/definitions/portal_properties.yaml#/components/schemas/UUID'
        name:
          type: string
          example: Nice Product
          description: the name of the product
          nullable: true
          readOnly: true
        description:
          type: string
          example: A nice product for customers to read about and consume
          description: a description of the product
          readOnly: true
        has_documentation:
          type: boolean
          example: true
          description: Whether the product has documents associated with it.
          readOnly: true
        created_at:
          $ref: '../../../../common/definitions/portal_properties.yaml#/components/schemas/CreatedAt'
        updated_at:
          $ref: '../../../../common/definitions/portal_properties.yaml#/components/schemas/UpdatedAt'
        versions:
          type: array
          items:
            additionalProperties: false
            type: object
            required:
              - id
              - created_at
              - updated_at
              - version
              - deprecated
            properties:
              id:
                $ref: '../../../../common/definitions/portal_properties.yaml#/components/schemas/UUID'
              created_at:
                $ref: '../../../../common/definitions/portal_properties.yaml#/components/schemas/CreatedAt'
              updated_at:
                $ref: '../../../../common/definitions/portal_properties.yaml#/components/schemas/UpdatedAt'
              version:
                type: string
                example: v2.0.0
                description: Name of product version.
                readOnly: true
              deprecated:
                description: Whether the version is deprecated.
                type: boolean
                example: true
                readOnly: true
    SearchIndicesParameters:
      title: 'SearchIndicesParameters'
      type: string
      enum:
        - product-catalog
    SearchQueryParameters:
      title: 'SearchQueryParameters'
      type: string
    SearchJoinParameters:
      title: 'SearchJoinParameters'
      type: string
      description: Accepted values are `versions` and `versions.documents`. Use commas to separate multiple values.
      example: versions,versions.documents
  examples:
    SearchResponseExample:
      value:
        data:
          - index: product-catalog
            source:
              created_at: '2023-01-19T17:41:55.896Z'
              updated_at: '2023-01-20T17:41:55.896Z'
              id: e35b0beb-c3f7-4f8f-95f7-cd8ff0ee478e
              name: Great Product
              description: Great products are built with great care
              has_documentation: true
              versions:
                - created_at: '2023-01-19T17:41:55.896Z'
                  updated_at: '2023-01-20T17:41:55.896Z'
                  id: b35b0beb-c3f7-4f8f-95f7-cd8ff0ee478e
                  version: v0
                  deprecated: false
                - created_at: '2022-01-19T17:41:55.896Z'
                  updated_at: '2022-01-19T17:41:55.896Z'
                  id: 455b0beb-c3f7-4f8f-95f7-cd8ff0ee478e
                  version: v1
                  deprecated: false
        meta:
          page:
            number: 1
            size: 10
            total: 4
tags:
  - name: search
    description: The API for Konnect Portal Search.
