openapi: 3.0.0
info:
  title: Portal Developer API
  version: 2.0.0
  description: The API for Konnect Portal Developers.
  contact:
    name: Kong
    url: 'https://cloud.konghq.com'
paths:
  /api/v2/developer:
    post:
      operationId: register
      summary: Register
      description: Register to the developer portal
      requestBody:
        description: Developer registration
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterPayload'
      responses:
        '201':
          description: the developer has been properly registered.
        '400':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/BadRequest'
        '500':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/Internal'
      tags:
        - developer
  /api/v2/developer/password-reset:
    post:
      operationId: reset-password
      summary: Password Reset
      description: |
        Starts the password reset flow for the desired account. An email
        will be sent to the email address to initiate the password reset flow.
      requestBody:
        description: Developer registration
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordPayload'
      responses:
        '200':
          description: the password reset flow has been initiated.
        '400':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/BadRequest'
        '500':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/Internal'
      tags:
        - developer
  /api/v2/developer/me:
    get:
      summary: Retrieve My Account
      tags:
        - developer
      responses:
        '200':
          $ref: '#/components/responses/MeResponse'
        '401':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/Unauthorized'
        '500':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/Internal'
      operationId: get-developer-me
      description: Returns info about the current developer.
components:
  responses:
    MeResponse:
      description: Response from me endpoint.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Developer'
  schemas:
    Developer:
      title: Developer
      type: object
      description: A developer is an individual who can use a developer portal.
      additionalProperties: false
      properties:
        id:
          type: string
          format: uuid
          example: 7f9fd312-a987-4628-b4c5-bb4f4fddd5f7
          readOnly: true
        email:
          type: string
          format: email
          example: developer@email.com
          maxLength: 250
        full_name:
          type: string
          pattern: '^[\w \W]+$'
          example: API Developer
          maxLength: 250
        created_at:
          type: string
          format: date-time
          example: '2022-02-07T17:46:57.52Z'
          readOnly: true
        updated_at:
          type: string
          format: date-time
          example: '2022-10-08T17:00:00.52Z'
          readOnly: true
      required:
        - full_name
        - email
    RegisterPayload:
      title: register payload
      description: |
        Payload required to be sent to register a developer to the
        portal.
      type: object
      additionalProperties: false
      properties:
        email:
          type: string
          format: email
          example: developer@konghq.com
        full_name:
          type: string
          minLength: 1
          maxLength: 256
          example: Jane Doe
      required:
        - full_name
        - email
    ResetPasswordPayload:
      title: reset password payload
      description: |
        Payload required to start the reset password flow
      type: object
      additionalProperties: false
      properties:
        email:
          type: string
          format: email
          example: developer@konghq.com
      required:
        - email
tags:
  - name: developer
    description: Portal Developer API
