workflowVersion: 1.0.0
speakeasyVersion: 1.602.0
sources:
    kong:
        inputs:
            - location: openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/kong/kong/kong
targets:
    terraform:
        target: terraform
        source: kong
