workflowVersion: 1.0.0
speakeasyVersion: 1.253.2
sources:
    konnect-api:
        inputs:
            - location: openapi.yaml
targets:
    terraform-provider-konnect:
        target: terraform
        source: konnect-api
        output: .
