openapi: 3.0.3
info:
  title: Portal Products API
  version: 2.0.0
  description: N/A (this description is removed during bundling)
  contact:
    name: Kong
    url: 'https://cloud.konghq.com'
paths:
  /api/v2/products/{productId}:
    get:
      summary: Get a product
      description: Gets the details for an existing published product.
      operationId: get-product
      parameters:
        - $ref: '#/components/parameters/ProductId'
      responses:
        '200':
          $ref: '#/components/responses/ProductGet'
        '400':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/BadRequest'
        '401':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/Unauthorized'
        '404':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/NotFound'
      tags:
        - products
      security:
        - portalAccessToken: []
        - {}
  /api/v2/products:
    get:
      summary: List Products
      description: Returns a paginated list of published API Products.
      operationId: list-products
      parameters:
        - $ref: '../../../../common/definitions/metadatas.yaml#/components/parameters/PageSize'
        - $ref: '../../../../common/definitions/metadatas.yaml#/components/parameters/PageNumber'
        - $ref: '../../../../common/definitions/filter_parameters.yaml#/components/parameters/FilterByNameEquality'
        - $ref: '../../../../common/definitions/filter_parameters.yaml#/components/parameters/FilterByNameEqualityShort'
        - $ref: '../../../../common/definitions/filter_parameters.yaml#/components/parameters/FilterByNameContains'
        - $ref: '../../../../common/definitions/filter_parameters.yaml#/components/parameters/FilterByDescriptionEquality'
        - $ref: '../../../../common/definitions/filter_parameters.yaml#/components/parameters/FilterByDescriptionEqualityShort'
        - $ref: '../../../../common/definitions/filter_parameters.yaml#/components/parameters/FilterByDescriptionContains'
        - $ref: '../../../../common/definitions/filter_parameters.yaml#/components/parameters/FilterByIdEquality'
        - $ref: '../../../../common/definitions/filter_parameters.yaml#/components/parameters/FilterByIdEqualityShort'
      responses:
        '200':
          $ref: '#/components/responses/ProductList'
        '400':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/BadRequest'
        '401':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/Unauthorized'
      tags:
        - products
      security:
        - portalAccessToken: []
        - {}
  /api/v2/products/{productId}/versions:
    get:
      summary: Get page of product versions
      description: Returns paginated list of versions of a given product.
      operationId: list-product-versions
      parameters:
        - $ref: '#/components/parameters/ProductId'
        - $ref: '../../../../common/definitions/metadatas.yaml#/components/parameters/PageSize'
        - $ref: '../../../../common/definitions/metadatas.yaml#/components/parameters/PageNumber'
        - $ref: '../../../../common/definitions/filter_parameters.yaml#/components/parameters/FilterByNameEquality'
        - $ref: '../../../../common/definitions/filter_parameters.yaml#/components/parameters/FilterByNameEqualityShort'
        - $ref: '../../../../common/definitions/filter_parameters.yaml#/components/parameters/FilterByNameContains'
      responses:
        '200':
          $ref: '#/components/responses/ProductListVersions'
        '400':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/BadRequest'
        '401':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/Unauthorized'
        '404':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/NotFound'
      tags:
        - versions
      security:
        - portalAccessToken: []
        - {}
  /api/v2/products/{productId}/versions/{versionId}:
    get:
      summary: Get product version
      description: Gets the details for an existing product version.
      operationId: get-product-version
      parameters:
        - $ref: '#/components/parameters/ProductId'
        - $ref: '#/components/parameters/ProductVersionId'
      responses:
        '200':
          $ref: '#/components/responses/ProductVersionGet'
        '400':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/BadRequest'
        '401':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/Unauthorized'
        '404':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/NotFound'
      tags:
        - versions
      security:
        - portalAccessToken: []
        - {}
  /api/v2/products/{productId}/versions/{versionId}/spec:
    get:
      summary: Get spec for product version
      description: Returns the API specification document attached to given product version. Currently only OpenAPI is supported.
      operationId: get-product-version-spec
      parameters:
        - $ref: '#/components/parameters/ProductId'
        - $ref: '#/components/parameters/ProductVersionId'
      responses:
        '200':
          $ref: '#/components/responses/ProductVersionSpecGet'
        '204':
          description: No specification is defined for the version.
        '400':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/BadRequest'
        '401':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/Unauthorized'
        '404':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/NotFound'
      tags:
        - versions
      security:
        - portalAccessToken: []
        - {}
  /api/v2/products/{productId}/versions/{versionId}/spec/operations:
    get:
      summary: Get operations in version spec
      description: Returns list of operations used in the API specification document attached to given product version.
      operationId: get-product-version-spec-operations
      parameters:
        - $ref: '#/components/parameters/ProductId'
        - $ref: '#/components/parameters/ProductVersionId'
      responses:
        '200':
          $ref: '#/components/responses/ProductVersionSpecOperationsGet'
        '204':
          description: Response when there are no operations to send because no spec is defined for the version.
        '400':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/BadRequest'
        '401':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/Unauthorized'
        '404':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/NotFound'
      tags:
        - versions
      security:
        - portalAccessToken: []
        - {}
  /api/v2/products/{productId}/documents:
    get:
      summary: List product documents
      description: Returns a list of documents that are associated with a given product. The list is paginated, and is in either a list or tree format (based on the Accept header).
      operationId: list-product-documents
      parameters:
        - $ref: '#/components/parameters/ProductId'
        - in: header
          name: Accept
          schema:
            $ref: '../../../../common/definitions/documenthub.yaml#/components/schemas/DocumentContentTypeEnum'
        - $ref: '../../../../common/definitions/metadatas.yaml#/components/parameters/PageSize'
        - $ref: '../../../../common/definitions/metadatas.yaml#/components/parameters/PageNumber'
      responses:
        '200':
          description: Lists documents for a given product.
          content:
            'application/json':
              schema:
                $ref: '../../../../common/definitions/documenthub.yaml#/components/schemas/ListDocuments'
            'application/konnect.document-tree+json':
              schema:
                $ref: '../../../../common/definitions/documenthub.yaml#/components/schemas/ListDocumentsTree'
        '400':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/BadRequest'
        '401':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/Unauthorized'
        '404':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/NotFound'
      tags:
        - documentation
      security:
        - portalAccessToken: []
        - {}
  /api/v2/products/{productId}/documents/{documentId}:
    get:
      summary: Get one product document
      description: Returns the specified document from the product's document tree.
      operationId: get-product-document
      parameters:
        - in: header
          name: Accept
          schema:
            $ref: '../../../../common/definitions/documenthub.yaml#/components/schemas/DocumentFormatContentTypeEnum'
        - $ref: '#/components/parameters/ProductId'
        - $ref: '#/components/parameters/DocumentId'
      responses:
        '200':
          $ref: '#/components/responses/ProductDocumentGet'
        '400':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/BadRequest'
        '401':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/Unauthorized'
        '404':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/NotFound'
      tags:
        - documentation
      security:
        - portalAccessToken: []
        - {}
components:
  securitySchemes:
    portalAccessToken:
      $ref: '../../../../common/definitions/security.yaml#/components/securitySchemes/portalAccessToken'
  parameters:
    ProductId:
      name: productId
      in: path
      required: true
      description: Contains a unique identifier used by the Portal API for this resource.
      schema:
        type: string
        format: uuid
    ProductVersionId:
      name: versionId
      in: path
      required: true
      description: Contains a unique identifier used by the Portal API for this resource.
      schema:
        type: string
        format: uuid
    DocumentId:
      name: documentId
      in: path
      required: true
      description: Contains a unique identifier used by the Portal API for this resource.
      schema:
        type: string
        format: uuid
  responses:
    ProductGet:
      description: Response for a single product's details.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Product'
    ProductList:
      description: Response for a list of products.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProductListPage'
    ProductListVersions:
      description: Paginated list of versions of an API Product.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProductVersionListPage'
    ProductVersionGet:
      description: Product version details.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProductVersion'
    ProductVersionSpecGet:
      description: Product version spec document.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProductVersionSpec'
    ProductVersionSpecOperationsGet:
      description: Product version spec operations.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProductVersionSpecOperations'
    ProductDocumentGet:
      description: Details for a single document for a given product.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProductDocumentRaw'
        application/konnect.document-nodes+json:
          schema:
            $ref: '#/components/schemas/ProductDocument'
  schemas:
    Product:
      title: Product
      type: object
      additionalProperties: false
      required:
        - id
        - created_at
        - updated_at
        - name
      properties:
        id:
          $ref: '../../../../common/definitions/portal_properties.yaml#/components/schemas/UUID'
        created_at:
          $ref: '../../../../common/definitions/portal_properties.yaml#/components/schemas/CreatedAt'
        updated_at:
          $ref: '../../../../common/definitions/portal_properties.yaml#/components/schemas/UpdatedAt'
        name:
          type: string
          example: Billing
          description: Name of product.
        description:
          type: string
          example: API for billing functions
        labels:
          type: object
    ProductListPage:
      title: ProductListPage
      type: object
      properties:
        meta:
          $ref: '../../../../common/definitions/metadatas.yaml#/components/schemas/PaginatedMeta'
        data:
          type: array
          items:
            $ref: '#/components/schemas/Product'
    ProductVersion:
      type: object
      additionalProperties: false
      properties:
        id:
          $ref: '../../../../common/definitions/portal_properties.yaml#/components/schemas/UUID'
        created_at:
          $ref: '../../../../common/definitions/portal_properties.yaml#/components/schemas/CreatedAt'
        updated_at:
          $ref: '../../../../common/definitions/portal_properties.yaml#/components/schemas/UpdatedAt'
        name:
          type: string
          example: v2.0.0
          description: Name of product version.
        deprecated:
          type: boolean
          description: If true, product version is deprecated.
        registration_configs:
          description: Configurations for how the product version is able to be registered for by applications.
          type: array
          items:
            type: object
            required:
              - name
            properties:
              name:
                type: string
                enum: [ key-auth, openid-connect ]
      required:
        - id
        - created_at
        - updated_at
        - name
        - deprecated
        - registration_configs
    ProductVersionListPage:
      title: ProductVersionListPage
      type: object
      properties:
        meta:
          $ref: '../../../../common/definitions/metadatas.yaml#/components/schemas/PaginatedMeta'
        data:
          type: array
          items:
            $ref: '#/components/schemas/ProductVersion'
    ProductVersionSpec:
      type: object
      title: Product Version Spec Document
      description: API specification document for a product version.
      properties:
        api_type:
          $ref: '#/components/schemas/ApiTypeEnum'
        content:
          type: string
      required:
      - api_type
      - content 
    ProductVersionSpecOperations:
      type: object
      title: Operations in product version spec document
      description: List of every operation detailed in a product version spec document.
      required:
        - api_type
        - operations
      properties:
        api_type:
          $ref: '#/components/schemas/ApiTypeEnum'
        operations:
          type: array
          items:
            type: object
            required:
              - path
              - method
              - operation_id
              - tags
              - summary
              - deprecated
            properties:
              path:
                type: string
                example: /pet
              method:
                type: string
                enum: [get, patch, post, put, delete, options, connect, trace]
                example: post
              operation_id:
                type: string
                nullable: true
                example: "addPet"
              tags:
                type: array
                items:
                  type: string
                  example: "pet"
              summary:
                type: string
                nullable: true
                example: "Add a new Pet to the store"
              deprecated:
                type: boolean
    ApiTypeEnum:
      type: string
      enum:
      - openapi
    ProductDocument:
      type: object
      title: Document
      description: A document for a product. This is a document that is not a part of the API specification.
      required:
        - id
        - slug
        - title
        - content
      properties:
        id:
          allOf:
            - $ref: '../../../../common/definitions/portal_properties.yaml#/components/schemas/UUID'
            - description: Contains a unique identifier used by the DocumentHub service for this resource.
        parent_document_id:
          type: string
          format: uuid
          description: Contains a unique identifier used by the DocumentHub service for this resource.
          nullable: true
          example: dd4e1b98-3629-4dd3-acc0-759a726ffee2
        slug:
          type: string
          description: Slug of the document. This is used in the URL to identify the document.
          example: getting-started
        content:
          $ref: '../../../../common/definitions/documenthub_nodes.yaml#/components/schemas/DocumentBlock'
        title:
          type: string
          description: Title of the document. This is used in the Portal UI to identify the document.
          example: Hello World
    ProductDocumentRaw:
      type: object
      title: Document
      description: A document for a product. This is a document that is not a part of the API specification.
      required:
        - id
        - slug
        - title
        - content
      properties:
        id:
          allOf:
            - $ref: '../../../../common/definitions/portal_properties.yaml#/components/schemas/UUID'
            - description: Contains a unique identifier used by the DocumentHub service for this resource.
        parent_document_id:
          type: string
          format: uuid
          description: Contains a unique identifier used by the DocumentHub service for this resource.
          nullable: true
          example: dd4e1b98-3629-4dd3-acc0-759a726ffee2
        slug:
          type: string
          description: Slug of the document. This is used in the URL to identify the document.
          example: getting-started
        content:
          type: string
          description: Markdown document
          example: |
            # My Kong api
            
            This api is powered by Konnect
        title:
          type: string
          description: Title of the document. This is used in the Portal UI to identify the document.
          example: Hello World
tags:
  - name: products
    description: The API for Konnect Portal Products.
  - name: versions
    description: The API for Konnect Portal Product Versions.
  - name: documentation
    description: The API for Konnect Portal Product Documentation.
