openapi: 3.0.0
info:
  title: Portal Authentication API
  version: 2.0.0
  description: |
    The API for Konnect Portal authentication.
  contact:
    name: Kong
    url: 'https://cloud.konghq.com'
paths:
  /api/v2/developer/authenticate:
    post:
      x-internal: true
      summary: Authenticate
      description: This endpoint allows a developer to authenticate to their portal using a username and password.
      operationId: authenticate
      requestBody:
        $ref: '#/components/requestBodies/AuthenticateRequest'
      responses:
        '204':
          description: No Content
          headers:
            Set-Cookie:
              schema:
                type: string
                example: |
                  portalaccesstoken=access12345; Path=/; Domain=example.us.portal.konghq.com; Expires=Thu, 20 Jul 2023 12:00:00 GMT; HttpOnly; Secure; SameSite=None
                  portalrefreshtoken=refresh12345; Path=/v2/refresh; Domain=example.us.portal.konghq.com; Expires=Thu, 20 Jul 2023 12:00:00 GMT; HttpOnly; Secure; SameSite=None
              description: The access and refresh tokens.
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
        - developer
  '/api/v2/developer/authenticate/sso':
    get:
      x-internal: true
      summary: Authenticate SSO
      description: This endpoint allows a developer to authenticate to their portal using an external IdP.
      operationId: authenticate-sso
      responses:
        '302':
          description: Found
        '400':
          $ref: '#/components/responses/BadRequest'
      tags:
        - developer
  /api/v2/developer/refresh:
    post:
      x-internal: true
      summary: Refresh Access Token
      description: This endpoint allows a developer to refresh their existing access token.
      operationId: refresh
      responses:
        '204':
          description: No Content
          headers:
            Set-Cookie:
              schema:
                type: string
                example: |
                  portalaccesstoken=access12345; Path=/; Domain=example.us.portal.konghq.com; Expires=Thu, 20 Jul 2023 12:00:00 GMT; HttpOnly; Secure; SameSite=None
                  portalrefreshtoken=refresh12345; Path=/v2/refresh; Domain=example.us.portal.konghq.com; Expires=Thu, 20 Jul 2023 12:00:00 GMT; HttpOnly; Secure; SameSite=None
        '401':
          $ref: ../../../../common/definitions/errors.yaml#/components/responses/Unauthorized
      tags:
        - developer
  /api/v2/developer/logout:
    post:
      x-internal: true
      summary: Logout
      description: This endpoint allows a developer to logout of the portal. This operation revokes all active tokens and clears the portal cookies.
      operationId: logout
      responses:
        '204':
          description: No Content
      tags:
        - developer
  /api/v2/developer/reset-password:
    post:
      x-internal: true
      summary: Reset Password
      description: 'This endpoint allows a developer to reset their password, using a reset token.'
      operationId: reset-password
      responses:
        '204':
          description: No Content
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: ../../../../common/definitions/errors.yaml#/components/responses/Unauthorized
        '404':
          $ref: '#/components/responses/NotFound'
        '410':
          $ref: '#/components/responses/Gone'
      tags:
        - developer
      requestBody:
        $ref: '#/components/requestBodies/ResetPasswordRequest'
    parameters: []
  /api/v2/developer/verify-email:
    post:
      x-internal: true
      summary: Verify Email
      description: This endpoint allows a new developer to verify their email.
      operationId: verify-email
      responses:
        '202':
          $ref: '#/components/responses/VerifyEmailResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '410':
          $ref: '#/components/responses/Gone'
      tags:
        - developer
      requestBody:
        $ref: '#/components/requestBodies/VerifyEmailRequest'
    parameters: []
components:
  requestBodies:
    AuthenticateRequest:
      description: The request schema for the authenticate endpoint.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AuthenticateRequest'
          examples:
            Authenticate-Request:
              $ref: '#/components/examples/Authenticate-Request'
    ResetPasswordRequest:
      description: The request schema for the reset password endpoint.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResetPasswordRequest'
          examples:
            ResetPasswordRequest:
              $ref: '#/components/examples/Reset-Password-Request'
    VerifyEmailRequest:
      description: The request schema for the verify email endpoint.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/VerifyEmailRequest'
          examples:
            VerifyEmailRequest:
              $ref: '#/components/examples/Verify-Email-Request'
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/problem+json:
          schema:
            $ref: '../../../../common/definitions/errors.yaml#/components/schemas/BadRequestError'
          examples:
            400-Invalid-Token:
              $ref: '#/components/examples/400-Invalid-Token'
    NotFound:
      description: Not Found
      content:
        application/problem+json:
          schema:
            $ref: '../../../../common/definitions/errors.yaml#/components/schemas/NotFoundError'
          examples:
            404-Token-Not-Found:
              $ref: '#/components/examples/404-Token-Not-Found'
    Gone:
      description: Gone
      content:
        application/problem+json:
          schema:
            $ref: '../../../../common/definitions/errors.yaml#/components/schemas/GoneError'
          examples:
            410-Expired-Token:
              $ref: '#/components/examples/410-Expired-Token'
    VerifyEmailResponse:
      description: The response schema for the verify email endpoint.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/VerifyEmailResponse'
          examples:
            VerifyEmailResponse:
              $ref: '#/components/examples/Verify-Email-Response'
  schemas:
    AuthenticateRequest:
      type: object
      additionalProperties: false
      example:
        $ref: '#/components/examples/Authenticate-Request/value'
      title: AuthenticateRequest
      description: The request schema for the authenticate endpoint.
      properties:
        username:
          type: string
          format: email
          example: developer@example.com
          writeOnly: true
        password:
          type: string
          format: password
          example: <!N0taP@$$w0rd!>
          writeOnly: true
      required:
        - username
        - password
    ResetPasswordRequest:
      title: ResetPasswordRequest
      type: object
      additionalProperties: false
      description: The request schema for the reset password endpoint.
      example:
        $ref: '#/components/examples/Reset-Password-Request/value'
      properties:
        password:
          type: string
          format: password
          example: <!N0taP@$$w0rd!>
          writeOnly: true
        token:
          type: string
          format: uuid
          example: c8efd006-d8e1-4743-b91b-f163b9eae06a
          writeOnly: true
      required:
        - password
        - token
    VerifyEmailRequest:
      title: VerifyEmailRequest
      type: object
      additionalProperties: false
      description: The request schema for the verify email endpoint.
      example:
        $ref: '#/components/examples/Verify-Email-Request/value'
      properties:
        token:
          type: string
          format: uuid
          example: c8efd006-d8e1-4743-b91b-f163b9eae06a
          writeOnly: true
      required:
        - token
    VerifyEmailResponse:
      title: VerifyEmailResponse
      type: object
      additionalProperties: false
      description: The response schema for the verify email endpoint.
      example:
        $ref: '#/components/examples/Verify-Email-Response/value'
      properties:
        email:
          type: string
          format: email
          example: developer@example.com
          readOnly: true
        token:
          type: string
          format: uuid
          example: c8efd006-d8e1-4743-b91b-f163b9eae06a
          readOnly: true
  examples:
    Authenticate-Request:
      value:
        username: developer@example.com
        password: <!N0taP@$$w0rd!>
    Reset-Password-Request:
      value:
        password: <!D3finitelyN0taP@$$w0rd!>
        token: c8efd006-d8e1-4743-b91b-f163b9eae06a
    Verify-Email-Request:
      value:
        token: c8efd006-d8e1-4743-b91b-f163b9eae06a
    Verify-Email-Response:
      value:
        email: developer@example.com
        token: c8efd006-d8e1-4743-b91b-f163b9eae06a
    400-Invalid-Token:
      value:
        status: 400
        title: Bad Request
        instance: 'konnect:trace:8988732526256293040'
        detail: The provided token is invalid
        invalid_parameters:
          - field: token
            reason: invalid ID format
    404-Token-Not-Found:
      value:
        status: 400
        title: Not Found
        instance: 'konnect:trace:8988732526256293040'
        detail: The provided token was not found
    410-Expired-Token:
      value:
        status: 410
        title: Gone
        instance: 'konnect:trace:8988732526256293040'
        detail: The token has expired
tags:
  - name: developer
    description: API for managing a Konnect Portal Developer.
