openapi: 3.0.3
info:
    title: DocumentHub Developer Api v2
    description: DocumentHub developer Api
    version: '0.0.1'
    contact:
      name: Kong
      url: 'https://konghq.com'
servers:
  - url: 'http://localhost:4400/developer/v2'
    description: Local
  - url: 'http://documenthub.documenthub.svc.cluster.local:4400/developer/v2'
    description: Konnect cluster
paths:
  /collections/{collectionId}/documents:
    get:
      summary: List collection documents
      description: List documents in a collection
      operationId: listDocuments
      parameters:
        - $ref: '#/components/parameters/collectionId'
        - $ref: '../../../../common/definitions/metadatas.yaml#/components/parameters/PageSize'
        - $ref: '../../../../common/definitions/metadatas.yaml#/components/parameters/PageNumber'
        - schema:
            type: string
            example: 'filter[name]=my-doc'
          in: query
          name: 'filter[field]'
          description: |
            A field to filter on. Supported fields: slug, metadata.
      responses:
        '200':
          description: Documents in the collection
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ListDocuments'
            'application/vnd.konnect.document-tree+json':
              schema:
                $ref: '#/components/schemas/ListDocumentsTree'
        '404':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/NotFound'
      tags:
        - Documents
  /collections/{collectionId}/documents/{documentId}:
    get:
      summary: Get the document
      description: Get the document
      operationId: getDocument
      parameters:
        - in: header
          name: Accept
          schema:
            $ref: '../../documenthub/common/v2/documenthub.yaml#/components/schemas/DocumentFormatContentTypeEnum'
        - $ref: '#/components/parameters/collectionId'
        - $ref: '#/components/parameters/documentId'
      responses:
        '200':
          description: Document
          content:
            text/markdown:
              schema:
                type: string
                description: the markdown content
            'application/json':
              schema:
                $ref: '#/components/schemas/DocumentRaw'
            application/vnd.konnect.document-nodes+json:
              schema:
                $ref: '#/components/schemas/Document'
        '404':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/NotFound'
      tags:
        - Documents
components:
  securitySchemes:
    portalAccessToken:
      $ref: '../../../../common/definitions/security.yaml#/components/securitySchemes/portalAccessToken'
  schemas:
    ListDocumentsTree:
      type: object
      required:
      - meta
      - data
      properties:
        meta:
          $ref: '../../../../common/definitions/metadatas.yaml#/components/schemas/PaginatedMeta'
        data:
          type: array
          items:
            $ref: '#/components/schemas/DocumentTree'
    ListDocuments:
      type: object
      additionalProperties: false
      required:
      - meta
      - data
      properties:
        meta:
          $ref: '../../../../common/definitions/metadatas.yaml#/components/schemas/PaginatedMeta'
        data:
          type: array
          items:
            $ref: '#/components/schemas/DocumentItem'
    DocumentItem:
      type: object
      title: Document item
      additionalProperties: false
      required:
      - id
      - parent_document_id
      - slug
      - title
      - metadata
      - created_at
      - updated_at
      properties:
        id:
          type: string
          format: uuid
          description: the id of the document
          example: d32d905a-ed33-46a3-a093-d8f536af9a8a
        parent_document_id:
          type: string
          format: uuid
          description: the id of the parent document
          nullable: true
          example: dd4e1b98-3629-4dd3-acc0-759a726ffee2
        slug:
          type: string
          description: the slug of the document
          example: getting-started
        title:
          type: string
          description: the title of the document
          example: Getting Started
        metadata:
          $ref: '../../documenthub/common/v2/documenthub.yaml#/components/schemas/Metadata'
        created_at:
          $ref: '../../../../common/definitions/properties.yaml#/components/schemas/CreatedAt'
        updated_at:
          $ref: '../../../../common/definitions/properties.yaml#/components/schemas/UpdatedAt'
    DocumentRaw:
      type: object
      title: Document
      description: a document
      required:
      - id
      - slug
      - revision
      - created_at
      - updated_at
      properties:
        id:
          type: string
          format: uuid
          description: the id of the document
          example: d32d905a-ed33-46a3-a093-d8f536af9a8a
        parent_document_id:
          type: string
          format: uuid
          description: the id of the parent document
          nullable: true
          example: dd4e1b98-3629-4dd3-acc0-759a726ffee2
        slug:
          type: string
          description: the slug of the document
          example: getting-started
        revision:
          $ref: '#/components/schemas/RevisionRaw'
        created_at:
          $ref: '../../../../common/definitions/properties.yaml#/components/schemas/CreatedAt'
        updated_at:
          $ref: '../../../../common/definitions/properties.yaml#/components/schemas/UpdatedAt'
    RevisionRaw:
      type: object
      title: Revision
      description: revision of a document
      required:
        - id
        - document_id
        - content
        - metadata
        - title
      properties:
        id:
          type: string
          format: uuid
          description: the id of the revision
          example: d32d905a-ed33-46a3-a093-d8f536af9a8a
        document_id:
          type: string
          format: uuid
          description: the id of the document
          example: d32d905a-ed33-46a3-a093-d8f536af9a8a
        content:
          type: string
          description: Markdown document
        metadata:
          $ref: '../../documenthub/common/v2/documenthub.yaml#/components/schemas/Metadata'
        title:
          type: string
          description: the title of the document
          example: Hello World
    ListDocumentCollectionResponse:
      type: object
      properties:
        meta:
          $ref: '../../../../common/definitions/metadatas.yaml#/components/schemas/PaginatedMeta'
        data:
          type: array
          items:
            $ref: '#/components/schemas/Document'
    Document:
      type: object
      title: Document
      description: a document
      required:
      - id
      - slug
      - meta
      - title
      - content
      properties:
        id:
          type: string
          format: uuid
          description: the id of the document
          example: d32d905a-ed33-46a3-a093-d8f536af9a8a
        parent_document_id:
          type: string
          format: uuid
          description: the id of the parent document
          nullable: true
          example: dd4e1b98-3629-4dd3-acc0-759a726ffee2
        slug:
          type: string
          description: the slug of the document
          example: getting-started
        content:
          $ref: '../../documenthub/common/v2/documenthub_nodes.yaml#/components/schemas/DocumentBlock'
        meta:
          type: object
          description: the metadata of the document
          example: {
              "title": "Hello World",
              "description": "This is a description",
              "keywords": "hello, world"
            }
        title:
          type: string
          description: the title of the document
          example: Hello World
    DocumentTree:
      type: object
      title: DocumentTree
      description: a document tree
      required:
      - id
      - title
      - slug
      - metadata
      - children
      properties:
        id:
          type: string
          format: uuid
          example: d32d905a-ed33-46a3-a093-d8f536af9a8a
        parent_document_id:
          type: string
          format: uuid
          nullable: true
          example: dd4e1b98-3629-4dd3-acc0-759a726ffee2
        title:
          type: string
          description: the title of the document
          example: Getting Started
        slug:
          type: string
          description: the slug of the document
          example: getting-started
        metadata:
          $ref: '../../documenthub/common/v2/documenthub.yaml#/components/schemas/Metadata'
        children:
          type: array
          items:
            $ref: '#/components/schemas/DocumentTree'
  requestBodies: {}
  responses: {}
  parameters:
    collectionId:
      name: collectionId
      in: path
      required: true
      description: Targeted collection
      example: bb84c46a-432d-4314-81e4-478614a52dcb
      schema:
        type: string
        format: uuid
    documentId:
      name: documentId
      in: path
      required: true
      description: Targeted document
      example: bb84c46a-432d-4314-81e4-478614a52dcb
      schema:
        type: string
        format: uuid
security:
  - portalAccessToken: []
tags:
  - name: Documents
    description: document operations