openapi: 3.0.0
info:
  title: Portal Registrations API
  version: 2.0.0
  description: |
    The API for Konnect Portal application registrations. If the portal is public
    all of the described endpoints will return a 404 error
  contact:
    name: Kong
    url: 'https://cloud.konghq.com'
paths:
  /api/v2/applications/{applicationId}/registrations:
    get:
      summary: Get application registrations
      description: This endpoint lists product registrations for an application
      operationId: get-many-application-registrations
      parameters:
        - $ref: '#/components/parameters/ApplicationId'
      responses:
        '200':
          $ref: '#/components/responses/GetManyRegistrations'
        '400':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/BadRequest'
        '401':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/Unauthorized'
        '404':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/NotFound'
      tags:
        - registrations
    post:
      summary: Register an application for a product
      description: This endpoint registers an application for a product
      operationId: create-application-registration
      parameters:
        - $ref: '#/components/parameters/ApplicationId'
      requestBody:
        $ref: '#/components/requestBodies/CreateRegistration'
      responses:
        '201':
          $ref: '#/components/responses/CreateRegistration'
        '400':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/BadRequest'
        '401':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/Unauthorized'
        '404':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/NotFound'
        '409':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/Conflict'
      tags:
        - registrations
  /api/v2/applications/{applicationId}/registrations/{registrationId}:
    get:
      summary: Get an application registration
      description: This endpoint retrieves the specified product registration for an application
      operationId: get-one-application-registration
      parameters:
        - $ref: '#/components/parameters/ApplicationId'
        - $ref: '#/components/parameters/RegistrationId'
      responses:
        '200':
          $ref: '#/components/responses/GetRegistration'
        '401':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/Unauthorized'
        '404':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/NotFound'
      tags:
        - registrations
    delete:
      summary: Delete an application registration
      description: This endpoint unregister an application for a product version
      operationId: delete-application-registration
      parameters:
        - $ref: '#/components/parameters/ApplicationId'
        - $ref: '#/components/parameters/RegistrationId'
      responses:
        '204':
          description: The registration has been deleted
        '401':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/Unauthorized'
        '404':
          $ref: '../../../../common/definitions/errors.yaml#/components/responses/NotFound'
      tags:
        - registrations
components:
  securitySchemes:
    portalAccessToken:
      $ref: '../../../../common/definitions/security.yaml#/components/securitySchemes/portalAccessToken'
  parameters:
    ApplicationId:
      name: applicationId
      in: path
      required: true
      description: Id of the targeted application
      schema:
        type: string
        format: uuid
    RegistrationId:
      name: registrationId
      in: path
      required: true
      description: Id of the targeted registration
      schema:
        type: string
        format: uuid
  responses:
    CreateRegistration:
      description: Registration creation response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GetRegistrationResponse'
    GetRegistration:
      description: Get registration response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GetRegistrationResponse'
    GetManyRegistrations:
      description: Get registrations response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GetManyRegistrationsResponse'
  requestBodies:
    CreateRegistration:
      description: Create an application registration
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateRegistrationPayload'
  schemas:
    CreateRegistrationPayload:
      additionalProperties: false
      type: object
      title: CreateRegistrationPayload
      description: an application registration payload
      required:
        - product_version_id
      properties:
        product_version_id:
          description: The UUID of the product version to register for
          type: string
          format: uuid
    GetManyRegistrationsResponse:
      additionalProperties: false
      type: object
      required:
      - data
      - meta
      properties:
        meta:
          $ref: '../../../../common/definitions/metadatas.yaml#/components/schemas/PaginatedMeta'
        data:
          type: array
          items:
            $ref: '#/components/schemas/GetRegistrationResponse'
    GetRegistrationResponse:
      additionalProperties: false
      type: object
      required:
        - id
        - status
        - application_id
        - product_id
        - product_version_id
        - created_at
        - updated_at
      properties:
        id:
          description: The UUID of the registration
          type: string
          format: uuid
        status:
          description: The approval status of the registration
          type: string
          enum:
            - approved
            - pending
            - rejected
            - revoked
        product_id:
          description: The UUID of the product registered for
          type: string
          format: uuid
        product_version_id:
          description: The UUID of the product version registered for
          type: string
          format: uuid
        application_id:
          description: The UUID of the application the registration is linked to
          type: string
          format: uuid
        created_at:
          description: ISO timestamp the registration record was created
          type: string
          format: date-time
        updated_at:
          description: ISO timestamp the registration record was last updated
          type: string
          format: date-time
security:
  - portalAccessToken: []
tags:
  - name: registrations
