// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/kong/terraform-provider-konnect/v3/internal/provider/typeconvert"
	"github.com/kong/terraform-provider-konnect/v3/internal/sdk/models/operations"
	"github.com/kong/terraform-provider-konnect/v3/internal/sdk/models/shared"
	"time"
)

func (r *MeteringMeterResourceModel) RefreshFromSharedMeter(ctx context.Context, resp *shared.Meter) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.Aggregation = types.StringValue(string(resp.Aggregation))
		r.CreatedAt = types.StringValue(typeconvert.TimeToString(resp.CreatedAt))
		r.DeletedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.DeletedAt))
		r.Description = types.StringPointerValue(resp.Description)
		if resp.Dimensions != nil {
			r.Dimensions = make(map[string]types.String, len(resp.Dimensions))
			for key, value := range resp.Dimensions {
				r.Dimensions[key] = types.StringValue(value)
			}
		}
		r.EventType = types.StringValue(resp.EventType)
		r.EventsFrom = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.EventsFrom))
		r.ID = types.StringValue(resp.ID)
		r.Key = types.StringValue(resp.Key)
		if len(resp.Labels) > 0 {
			r.Labels = make(map[string]types.String, len(resp.Labels))
			for key1, value1 := range resp.Labels {
				r.Labels[key1] = types.StringPointerValue(value1)
			}
		}
		r.Name = types.StringValue(resp.Name)
		r.UpdatedAt = types.StringValue(typeconvert.TimeToString(resp.UpdatedAt))
		r.ValueProperty = types.StringPointerValue(resp.ValueProperty)
	}

	return diags
}

func (r *MeteringMeterResourceModel) ToOperationsDeleteMeterRequest(ctx context.Context) (*operations.DeleteMeterRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var meterID string
	meterID = r.ID.ValueString()

	out := operations.DeleteMeterRequest{
		MeterID: meterID,
	}

	return &out, diags
}

func (r *MeteringMeterResourceModel) ToOperationsGetMeterRequest(ctx context.Context) (*operations.GetMeterRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var meterID string
	meterID = r.ID.ValueString()

	out := operations.GetMeterRequest{
		MeterID: meterID,
	}

	return &out, diags
}

func (r *MeteringMeterResourceModel) ToSharedCreateMeterRequest(ctx context.Context) (*shared.CreateMeterRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var name string
	name = r.Name.ValueString()

	description := new(string)
	if !r.Description.IsUnknown() && !r.Description.IsNull() {
		*description = r.Description.ValueString()
	} else {
		description = nil
	}
	labels := make(map[string]*string)
	for labelsKey := range r.Labels {
		labelsInst := new(string)
		if !r.Labels[labelsKey].IsUnknown() && !r.Labels[labelsKey].IsNull() {
			*labelsInst = r.Labels[labelsKey].ValueString()
		} else {
			labelsInst = nil
		}
		labels[labelsKey] = labelsInst
	}
	var key string
	key = r.Key.ValueString()

	aggregation := shared.Aggregation(r.Aggregation.ValueString())
	var eventType string
	eventType = r.EventType.ValueString()

	eventsFrom := new(time.Time)
	if !r.EventsFrom.IsUnknown() && !r.EventsFrom.IsNull() {
		*eventsFrom, _ = time.Parse(time.RFC3339Nano, r.EventsFrom.ValueString())
	} else {
		eventsFrom = nil
	}
	valueProperty := new(string)
	if !r.ValueProperty.IsUnknown() && !r.ValueProperty.IsNull() {
		*valueProperty = r.ValueProperty.ValueString()
	} else {
		valueProperty = nil
	}
	var dimensions map[string]string
	if r.Dimensions != nil {
		dimensions = make(map[string]string)
		for dimensionsKey := range r.Dimensions {
			var dimensionsInst string
			dimensionsInst = r.Dimensions[dimensionsKey].ValueString()

			dimensions[dimensionsKey] = dimensionsInst
		}
	}
	out := shared.CreateMeterRequest{
		Name:          name,
		Description:   description,
		Labels:        labels,
		Key:           key,
		Aggregation:   aggregation,
		EventType:     eventType,
		EventsFrom:    eventsFrom,
		ValueProperty: valueProperty,
		Dimensions:    dimensions,
	}

	return &out, diags
}
