// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/kong/terraform-provider-konnect/v2/internal/provider/typeconvert"
	"github.com/kong/terraform-provider-konnect/v2/internal/sdk/models/operations"
	"github.com/kong/terraform-provider-konnect/v2/internal/sdk/models/shared"
)

func (r *PortalDataSourceModel) ToOperationsGetPortalRequest(ctx context.Context) (*operations.GetPortalRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var portalID string
	portalID = r.ID.ValueString()

	out := operations.GetPortalRequest{
		PortalID: portalID,
	}

	return &out, diags
}

func (r *PortalDataSourceModel) RefreshFromSharedCreatePortalResponse(ctx context.Context, resp *shared.CreatePortalResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.ApplicationCount = types.Float64Value(resp.ApplicationCount)
		r.AutoApproveApplications = types.BoolValue(resp.AutoApproveApplications)
		r.AutoApproveDevelopers = types.BoolValue(resp.AutoApproveDevelopers)
		r.CreatedAt = types.StringValue(typeconvert.TimeToString(resp.CreatedAt))
		r.CustomClientDomain = types.StringPointerValue(resp.CustomClientDomain)
		r.CustomDomain = types.StringPointerValue(resp.CustomDomain)
		r.DefaultApplicationAuthStrategyID = types.StringPointerValue(resp.DefaultApplicationAuthStrategyID)
		r.DefaultDomain = types.StringValue(resp.DefaultDomain)
		r.Description = types.StringPointerValue(resp.Description)
		r.DeveloperCount = types.Float64Value(resp.DeveloperCount)
		r.DisplayName = types.StringValue(resp.DisplayName)
		r.ID = types.StringValue(resp.ID)
		r.IsPublic = types.BoolValue(resp.IsPublic)
		if len(resp.Labels) > 0 {
			r.Labels = make(map[string]types.String, len(resp.Labels))
			for key, value := range resp.Labels {
				r.Labels[key] = types.StringPointerValue(value)
			}
		}
		r.Name = types.StringValue(resp.Name)
		r.PublishedProductCount = types.Float64Value(resp.PublishedProductCount)
		r.RbacEnabled = types.BoolValue(resp.RbacEnabled)
		r.UpdatedAt = types.StringValue(typeconvert.TimeToString(resp.UpdatedAt))
	}

	return diags
}
