// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/kong/terraform-provider-konnect/v2/internal/provider/typeconvert"
	"github.com/kong/terraform-provider-konnect/v2/internal/sdk/models/operations"
	"github.com/kong/terraform-provider-konnect/v2/internal/sdk/models/shared"
)

func (r *PortalTeamResourceModel) RefreshFromSharedV2PortalTeamResponse(ctx context.Context, resp *shared.V2PortalTeamResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.CreatedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.CreatedAt))
		r.Description = types.StringPointerValue(resp.Description)
		r.ID = types.StringPointerValue(resp.ID)
		r.Name = types.StringPointerValue(resp.Name)
		r.UpdatedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.UpdatedAt))
	}

	return diags
}

func (r *PortalTeamResourceModel) ToOperationsCreatePortalTeamRequest(ctx context.Context) (*operations.CreatePortalTeamRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var portalID string
	portalID = r.PortalID.ValueString()

	v2PortalCreateTeamRequest, v2PortalCreateTeamRequestDiags := r.ToSharedV2PortalCreateTeamRequest(ctx)
	diags.Append(v2PortalCreateTeamRequestDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.CreatePortalTeamRequest{
		PortalID:                  portalID,
		V2PortalCreateTeamRequest: v2PortalCreateTeamRequest,
	}

	return &out, diags
}

func (r *PortalTeamResourceModel) ToOperationsDeletePortalTeamRequest(ctx context.Context) (*operations.DeletePortalTeamRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var teamID string
	teamID = r.ID.ValueString()

	var portalID string
	portalID = r.PortalID.ValueString()

	out := operations.DeletePortalTeamRequest{
		TeamID:   teamID,
		PortalID: portalID,
	}

	return &out, diags
}

func (r *PortalTeamResourceModel) ToOperationsGetPortalTeamRequest(ctx context.Context) (*operations.GetPortalTeamRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var teamID string
	teamID = r.ID.ValueString()

	var portalID string
	portalID = r.PortalID.ValueString()

	out := operations.GetPortalTeamRequest{
		TeamID:   teamID,
		PortalID: portalID,
	}

	return &out, diags
}

func (r *PortalTeamResourceModel) ToOperationsUpdatePortalTeamRequest(ctx context.Context) (*operations.UpdatePortalTeamRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var teamID string
	teamID = r.ID.ValueString()

	var portalID string
	portalID = r.PortalID.ValueString()

	v2PortalUpdateTeamRequest, v2PortalUpdateTeamRequestDiags := r.ToSharedV2PortalUpdateTeamRequest(ctx)
	diags.Append(v2PortalUpdateTeamRequestDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.UpdatePortalTeamRequest{
		TeamID:                    teamID,
		PortalID:                  portalID,
		V2PortalUpdateTeamRequest: v2PortalUpdateTeamRequest,
	}

	return &out, diags
}

func (r *PortalTeamResourceModel) ToSharedV2PortalCreateTeamRequest(ctx context.Context) (*shared.V2PortalCreateTeamRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var name string
	name = r.Name.ValueString()

	description := new(string)
	if !r.Description.IsUnknown() && !r.Description.IsNull() {
		*description = r.Description.ValueString()
	} else {
		description = nil
	}
	out := shared.V2PortalCreateTeamRequest{
		Name:        name,
		Description: description,
	}

	return &out, diags
}

func (r *PortalTeamResourceModel) ToSharedV2PortalUpdateTeamRequest(ctx context.Context) (*shared.V2PortalUpdateTeamRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	name := new(string)
	if !r.Name.IsUnknown() && !r.Name.IsNull() {
		*name = r.Name.ValueString()
	} else {
		name = nil
	}
	description := new(string)
	if !r.Description.IsUnknown() && !r.Description.IsNull() {
		*description = r.Description.ValueString()
	} else {
		description = nil
	}
	out := shared.V2PortalUpdateTeamRequest{
		Name:        name,
		Description: description,
	}

	return &out, diags
}
