// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type AuthStrategyKeyAuth struct {
	CredentialType types.String   `tfsdk:"credential_type"`
	ID             types.String   `tfsdk:"id"`
	KeyNames       []types.String `tfsdk:"key_names"`
	Name           types.String   `tfsdk:"name"`
}
