// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type CreateDcrConfigAuth0InRequest struct {
	InitialClientAudience     types.String `tfsdk:"initial_client_audience"`
	InitialClientID           types.String `tfsdk:"initial_client_id"`
	InitialClientSecret       types.String `tfsdk:"initial_client_secret"`
	UseDeveloperManagedScopes types.Bool   `tfsdk:"use_developer_managed_scopes"`
}
