// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type DatakitPluginMemory struct {
	DictionaryName types.String `tfsdk:"dictionary_name"`
}
