// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type MeshServiceItemStatus struct {
	Addresses          []Addresses          `tfsdk:"addresses"`
	DataplaneProxies   *DataplaneProxies    `tfsdk:"dataplane_proxies"`
	HostnameGenerators []HostnameGenerators `tfsdk:"hostname_generators"`
	TLS                *MeshServiceItemTLS  `tfsdk:"tls"`
	Vips               []Vip                `tfsdk:"vips"`
}
