// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type MeshItemTracingBackends struct {
	Conf     *Metadata    `tfsdk:"conf"`
	Name     types.String `tfsdk:"name"`
	Sampling *Sampling    `tfsdk:"sampling"`
	Type     types.String `tfsdk:"type"`
}
