// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type OauthConfig struct {
	AuthorizationEndpoint types.String `tfsdk:"authorization_endpoint"`
	ClientID              types.String `tfsdk:"client_id"`
	ClientSecret          types.String `tfsdk:"client_secret"`
	TokenEndpoint         types.String `tfsdk:"token_endpoint"`
}
