// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type Server struct {
	ForwardClientHeaders types.Bool    `tfsdk:"forward_client_headers"`
	Tag                  types.String  `tfsdk:"tag"`
	Timeout              types.Float64 `tfsdk:"timeout"`
}
