// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
)

type StorageConfig struct {
	Consul *Consul                         `tfsdk:"consul"`
	Kong   map[string]jsontypes.Normalized `tfsdk:"kong"`
	Redis  *AcmePluginRedis                `tfsdk:"redis"`
	Shm    *Shm                            `tfsdk:"shm"`
	Vault  *AcmePluginVault                `tfsdk:"vault"`
}
