openapi: "3.0.3"
info: 
  title: "Konnect API"
  description: "The Konnect platform API"
servers:
  - url: "https://us.api.konghq.com"
    description: "United-States Production region"
  - url: "https://eu.api.konghq.com"
    description: "Europe Production region"
  - url: "https://au.api.konghq.com"
    description: "Australia Production region"
  - url: "https://me.api.konghq.com"
    description: "Middle-East Production region"
  - url: "https://global.api.konghq.com"
    description: "Global Production"