openapi: 3.0.0
info:
  title: Portal
  version: 2.0.0
  description: N/A (this description is removed during bundling)
  contact:
    name: Kong
    url: https://cloud.konghq.com
paths:
  /api/v2/portal:
    get:
      operationId: get-portal-context
      summary: Get portal context
      description: Return the portal context object.
      responses:
        '200':
          $ref: '#/components/responses/GetPortalContextResponse'
      tags:
        - portal
      security:
        - {}
  /api/v2/portal/appearance:
    get:
      operationId: get-portal-appearance
      summary: Portal Appearance Details
      description: Gets appearance configuration object for the portal. This object is set in Konnect.
      responses:
        '200':
          $ref: '#/components/responses/GetPortalAppearanceResponse'
      tags:
        - portal
      security:
        - {}
  /api/v2/portal/logo:
    get:
      operationId: get-portal-logo
      summary: Portal Logo
      description: Gets logo of the developer portal. This object is set in Konnect.
      responses:
        '200':
          $ref: '#/components/responses/GetPortalLogoResponse'
      tags:
        - portal
      security:
        - {}
  /api/v2/portal/catalog-cover:
    get:
      operationId: get-portal-catalog-cover
      summary: Portal Catalog Cover Banner
      description: Gets cover banner for the developer portal. This object is set in Konnect.
      responses:
        '200':
          $ref: '#/components/responses/GetPortalCoverResponse'
      tags:
        - portal
      security:
        - {}
  /api/v2/portal/pages:
    get:
      x-unstable: true
      x-internal: true
      operationId: list-portal-pages
      summary: List Portal Pages
      description: >-
        Returns a paginated list of pages for the portal. Each page has a path, title, and content.
        Public pages will be returned for non-authenticated users, while both private and public pages will be returned for authenticated users.
      parameters:
        - $ref: '#/components/parameters/SortPortalPages'
        - $ref: '../../../common/definitions/metadatas.yaml#/components/parameters/PageSize'
        - $ref: '../../../common/definitions/metadatas.yaml#/components/parameters/PageNumber'
        - $ref: '../common/filter_parameters.yaml#/components/parameters/FilterByTitleEquality'
        - $ref: '../common/filter_parameters.yaml#/components/parameters/FilterByTitleEqualityShort'
        - $ref: '../common/filter_parameters.yaml#/components/parameters/FilterByTitleContains'
        - $ref: '../common/filter_parameters.yaml#/components/parameters/FilterByPathEquality'
        - $ref: '../common/filter_parameters.yaml#/components/parameters/FilterByPathEqualityShort'
        - $ref: '../common/filter_parameters.yaml#/components/parameters/FilterByPathContains'
        - $ref: '../common/filter_parameters.yaml#/components/parameters/FilterByPublicEquality'
        - $ref: '../common/filter_parameters.yaml#/components/parameters/FilterByPublicEqualityShort'
      responses:
        '200':
          $ref: '#/components/responses/ListPortalPagesResponse'
      tags:
        - portal
      security:
        - portalAccessToken: []
        - {}
  /api/v2/portal/pages/{pageId}:
    get:
      x-unstable: true
      x-internal: true
      operationId: get-portal-page
      summary: Get Portal Page
      description: >-
        Returns a single page for the portal. Each page has a path, title, and content.
        Public pages will be returned for non-authenticated users, while both private and public pages will be returned for authenticated users.
      parameters:
        - name: pageId
          in: path
          description: The unique identifier of the page
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          $ref: '#/components/responses/GetPortalPageResponse'
        '404':
          $ref: '../../../common/definitions/errors.yaml#/components/responses/NotFound'
      tags:
        - portal
      security:
        - portalAccessToken: []
        - {}
components:
  parameters:
    SortPortalPages:
      name: 'sort'
      description: |
        Sorts a collection of portal pages. Supported sort attributes are:
          - created_at
          - updated_at
          - path
          - title
          - public
      in: query
      required: false
      schema:
        type: string
  responses:
    GetPortalLogoResponse:
      description: Logo of the portal. Can be either png or jpg
      content:
        image/png:
          schema:
            type: string
            format: binary
        image/jpg:
          schema:
            type: string
            format: binary
    GetPortalCoverResponse:
      description: Cover of the portal. Can be either png or jpg
      content:
        image/png:
          schema:
            type: string
            format: binary
        image/jpg:
          schema:
            type: string
            format: binary
    GetPortalAppearanceResponse:
      description: portal appearance
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PortalAppearance'
    GetPortalContextResponse:
      description: portal context
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PortalContext'
    ListPortalPagesResponse:
      description: Paginated list of portal pages
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ListPortalPages'
          examples:
            ListPortalPageResponseExample1:
              value:
                data:
                  - id: 582b9327-3eba-4bfe-9438-6066840dbbca
                    title: 'Home'
                    path: '/'
                    public: true
                    created_at: '2021-09-01T00:00:00Z'
                    updated_at: '2021-09-01T00:00:00Z'
                meta:
                  page:
                    size: 10
                    total: 1
                    number: 1
    GetPortalPageResponse:
      description: A single portal page
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PortalPage'
          examples:
            PortalPageResponseExample1:
              value:
                id: 582b9327-3eba-4bfe-9438-6066840dbbca
                title: 'Home'
                path: '/'
                content: '# Welcome to the Developer Portal'
                public: true
                created_at: '2021-09-01T00:00:00Z'
                updated_at: '2021-09-01T00:00:00Z'
  schemas:
    PortalAppearance:
      title: Portal Appearance
      description: the portal appearance
      type: object
      additionalProperties: false
      properties:
        variables:
          type: object
          properties:
            catalog:
              type: object
              properties:
                logo:
                  type: object
                  properties:
                    url:
                      type: string
                cover:
                  type: object
                  properties:
                    url:
                      type: string
                primary_header:
                  type: object
                  properties:
                    text:
                      type: string
                welcome_message:
                  type: object
                  properties:
                    text:
                      type: string
        stylesheets:
          type: object
          properties:
            global:
              type: object
              properties:
                main:
                  type: object
                  properties:
                    data:
                      type: object
    PortalContext:
      title: Portal Context
      description: describe the portal execution context
      type: object
      additionalProperties: false
      properties:
        portal_id:
          type: string
          format: uuid
        org_id:
          type: string
          format: uuid
        featureset_id:
          type: string
        feature_set:
          type: string
          description: String that determines feature set group developer belongs to when logged in
        basic_auth_enabled:
          type: boolean
          description: Whether the portal can be accessed via email and password
        oidc_auth_enabled:
          type: boolean
          description: Whether the portal can be accessed via authentication with Single Sign On (SSO) through OpenID Connect (OIDC) from a third-party Identity Provider
        is_public:
          type: boolean
          description: Whether the portal catalog can be accessed by non-authenticated users
        rbac_enabled:
          type: boolean
          description: Whether the portal is protected with Role-Based Access Control
        dcr_provider_ids:
          type: array
          description: The unique identifiers of each available client provider when using Dynamic Client Registration
          items:
            type: string
            format: uuid
        allowed_time_period:
          type: string
          description: Allowed time period for Analytics queries
        name:
          type: string
          description: Name of the developer portal.
      required:
        - portal_id
        - org_id
        - is_public
        - featureset_id
        - basic_auth_enabled
        - oidc_auth_enabled
        - rbac_enabled
        - dcr_provider_ids
        - allowed_time_period
        - name
    PageId:
      title: Page ID
      description: The unique identifier of the page
      type: string
      format: uuid
      example: 582b9327-3eba-4bfe-9438-6066840dbbca
    PagePath:
      title: Page Path
      description: The path of the page with a leading slash
      type: string
      example: /my-page
    PageTitle:
      title: Page Title
      description: The title of the page
      type: string
      example: My Page
    PageContent:
      title: Page Content
      description: The renderable markdown content of the page
      type: string
      example: '# Welcome to the Developer Portal'
    PagePublicStatus:
      title: Page Public Status
      description: Whether the page is public or private. Private pages are only accessible to authenticated users.
      type: boolean
      example: true
    ListPortalPages:
      title: List Portal Pages
      description: A paginated list of pages for the portal
      type: object
      additionalProperties: false
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/PortalPageInfo'
        meta:
          $ref: '../../../common/definitions/metadatas.yaml#/components/schemas/PaginatedMeta'
    PortalPageInfo:
      title: Portal Page Info
      description: A single page for the portal
      type: object
      additionalProperties: false
      properties:
        id:
          $ref: '#/components/schemas/PageId'
        path:
          $ref: '#/components/schemas/PagePath'
        title:
          $ref: '#/components/schemas/PageTitle'
        public:
          $ref: '#/components/schemas/PagePublicStatus'
        created_at:
          $ref: '../../../common/definitions/konnect_properties.yaml#/components/schemas/CreatedAt'
        updated_at:
          $ref: '../../../common/definitions/konnect_properties.yaml#/components/schemas/UpdatedAt'
      required:
        - id
        - path
        - title
        - public
        - created_at
        - updated_at
    PortalPage:
      title: Portal Page
      description: A single page for the portal
      type: object
      additionalProperties: false
      properties:
        id:
          $ref: '#/components/schemas/PageId'
        title:
          $ref: '#/components/schemas/PageTitle'
        path:
          $ref: '#/components/schemas/PagePath'
        content:
          $ref: '#/components/schemas/PageContent'
        public:
          $ref: '#/components/schemas/PagePublicStatus'
        created_at:
          $ref: '../../../common/definitions/konnect_properties.yaml#/components/schemas/CreatedAt'
        updated_at:
          $ref: '../../../common/definitions/konnect_properties.yaml#/components/schemas/UpdatedAt'
      required:
        - id
        - title
        - path
        - content
        - public
        - created_at
        - updated_at
  securitySchemes:
    portalAccessToken:
      $ref: '../../../common/definitions/security.yaml#/components/securitySchemes/portalAccessToken'
tags:
  - name: portal
    description: The API for retrieving details about a single Konnect Portal.
