name: Bump Version
on:
  pull_request:
    types: [labeled, unlabeled]
jobs:
  check-semver-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit
      - uses: mheap/github-action-required-labels@388fd6af37b34cdfe5a23b37060e763217e58b03 # v5
        with:
          mode: exactly
          count: 1
          labels: "patch, minor, major"

  bump-version:
    needs: [check-semver-label]
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit
      - name: Install Speakeasy
        uses: mheap/setup-go-cli@fa9b01cdd4115eac636164f0de43bf7d51c82697 # v1
        with:
          owner: speakeasy-api
          repo: speakeasy
          cli_name: speakeasy
          package_type: zip
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.PAT }}
      - name: Reset gen.yaml to the version on main
        run: |
          git fetch origin main
          git checkout origin/main gen.yaml .speakeasy/gen.lock
      - name: Set bump (patch)
        run: |
          BUMP_TYPE=$(echo '${{ toJson(github.event.pull_request.labels.*.name) }}' | jq -r '.[]' | grep -E 'patch|minor|major')
          speakeasy bump $BUMP_TYPE
      - name: Commit SDK changes to the PR
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9
        with:
          add: .
          default_author: github_actor
          message: Bump gen.yaml based on label
