name: Bump Version
on:
  pull_request:
    types: [opened, labeled, unlabeled]
jobs:
  check-semver-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: "patch, minor, major"

  bump-version:
    needs: [check-semver-label]
    runs-on: ubuntu-latest
    steps:
      - name: Install Speakeasy
        uses: mheap/setup-go-cli@v1
        with:
          owner: speakeasy-api
          repo: speakeasy
          cli_name: speakeasy
          package_type: zip
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.PAT }}
      - name: Reset gen.yaml to the version on main
        run: |
          git fetch origin main
          git checkout origin/main gen.yaml .speakeasy/gen.lock
      - name: Set bump (patch)
        run: |
          BUMP_TYPE=$(echo '${{ toJson(github.event.pull_request.labels.*.name) }}' | jq -r '.[]' | grep -E 'patch|minor|major')
          speakeasy bump $BUMP_TYPE
      - name: Commit SDK changes to the PR
        uses: EndBug/add-and-commit@v9
        with:
          add: .
          default_author: github_actor
          message: Bump gen.yaml based on label
