name: Generate OAS Docs Files

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  generate-docs:
    name: Generates all OAS Docs Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install Dependencies
        run: npm install

      - name: Merge OAS in to konnect/portal
        run: |
          ./tools/merge-oas.sh

      - name: Process OpenAPI files
        run: |
          npm run generate-sdk-oas

      - name: Upload docs OAS files
        uses: actions/upload-artifact@v3
        with:
          name: docs-oas-files
          path: output/**/*-docs.yaml

      - name: Upload combined public OAS files
        uses: actions/upload-artifact@v3
        with:
          name: public-oas-files
          path: output/**/public.yaml
