name: Generate OAS Docs Files

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  generate-docs:
    name: Generates all OAS Docs Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install Dependencies
        run: npm ci

      - name: Bundle + Process OpenAPI specs
        run: |
          ./tools/run.sh

      - name: Check that /build/ is up to date
        run: |
          ./bin/fails_if_changed.sh

      - name: Upload combined public OAS files
        uses: actions/upload-artifact@v3
        with:
          name: public-oas-files
          path: build/complete/**/*.yaml

      - name: Upload computed OAS files per-service
        uses: actions/upload-artifact@v3
        with:
          name: computed-oas-files
          path: build/services/**/*.yaml
