name: Lint
on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
jobs:
  spectral:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Bundle Apis
        run: |
          npm ci
          npm run bundle-apis
      
      - name: Test common definitions
        run: npm run test:common
 
      - name: lint konnect definitions
        run : npx spectral lint 'src/konnect/definitions/**/openapi.yaml'

      - name: lint portal definitions
        run : npx spectral lint 'src/portal/definitions/**/openapi.yaml'

      - name: lint internal definitions
        run : npx spectral lint 'src/internal/definitions/**/openapi.yaml'

      - name: Lint OAS artifacts
        shell: bash
        run: |
          npm run lint:artifacts