name: Publish SDK Packages

on:
  push:
    branches:
      - main

jobs:
  publish-services:
    timeout-minutes: 30
    name: Publish Services (Internal use)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate packages + publish to NPM
        run: |
          ./tools/generate-service-packages.sh
        env:
          PUBLISH_TO_NPM: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  changes:
    timeout-minutes: 10
    name: Get Changed Spec Files
    runs-on: ubuntu-latest

    outputs:
      identity_spec_v3: ${{ steps.identity-v3.outputs.spec }}
      organization_settings_spec: ${{ steps.audit-logs.outputs.spec }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v2
        id: identity-v3
        with:
          filters: |
            spec:
              - 'src/konnect/definitions/identity/v3/openapi.yaml'
              - 'src/konnect/packages/identity/v3/npm/**'

      - uses: dorny/paths-filter@v2
        id: audit-logs
        with:
          filters: |
            spec:
              - 'src/konnect/definitions/audit-logs/v2/openapi.yaml'
              - 'src/konnect/packages/audit-logs/v2/npm/**'

  kauth-client-v3-axios-npm:
    timeout-minutes: 10
    name: Publish KAuth Client v3 Axios Package to NPM

    needs: changes
    if: ${{ needs.changes.outputs.identity_spec_v3 == 'true' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: |
          npm ci
          cd src/konnect/packages/identity/v3/npm
          npm ci

      - name: Bundle Apis
        run: npm run bundle-apis all-files

      - name: Validate Spec
        run: npm run validate:identity-v3-spec

      - name: Generate Client
        run: npm run generate:identity-v3-client

      - name: Publish to NPM Registry
        run: |
          cd src/konnect/packages/identity/v3/npm
          npm version --no-git-tag-version $(npm view @kong/kauth-client-v3-axios@latest version)
          npm version --no-git-tag-version patch
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  audit-logs-client-v2-axios-npm:
    timeout-minutes: 10
    name: Publish Organization Settings Client v2 Axios Package to NPM

    needs: changes
    if: ${{ needs.changes.outputs.organization_settings_spec == 'true' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: |
          npm ci
          cd src/konnect/packages/audit-logs/v2/npm
          npm ci

      - name: Bundle Apis
        run: npm run bundle-apis all-files

      - name: Validate Spec
        run: npm run validate:audit-logs-v2-spec

      - name: Generate Client
        run: npm run generate:audit-logs-v2-client

      - name: Publish to NPM Registry
        run: |
          cd src/konnect/packages/audit-logs/v2/npm
          npm version --no-git-tag-version $(npm view @kong/audit-logs-client-v2-axios@latest version)
          npm version --no-git-tag-version patch
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
