name: Terraform Provider Tests

on:
  pull_request:
    paths:
      - ".github/workflows/test.yaml"
      - "**.go"

permissions:
  contents: read

jobs:
  acceptance:
    name: Acceptance Tests (Terraform ${{ matrix.terraform-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Only test against one version for now as these tests are not
        # namespaced and will conflict
        terraform-version:
          - "1.11.*"
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: actions/setup-go@cd53bc84d5e2fd85362f4cb840513e06427082d3 # v4
        with:
          go-version-file: "go.mod"
      - uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2
        with:
          terraform_version: ${{ matrix.terraform-version }}
          terraform_wrapper: false
      - env:
          KONNECT_SPAT: ${{ secrets.KONNECT_SPAT }}
        run: make acceptance
